/*
 * Amazon Ads API - Sponsored Brands
 *
 * Use the Amazon Ads API for Sponsored Brands for campaign, ad group, keyword, negative keyword, drafts, Stores, landing pages, and Brands management operations. For more information about Sponsored Brands, see the [Sponsored Brands Support Center](https://advertising.amazon.com/help#GQFZA83P55P747BZ). For onboarding information, see the [account setup](https://advertising.amazon.com/API/docs/v3/guides/account_setup) topic.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredbrandsv3

// SbKeywordRecommendationGoal : Optionally indicate the desired goal of your campaign. Different keyword recommendations will be provided depending on your specified goal.  |Identifier|Description| |----------|-----------| |PAGE_VISIT| Boost the visits to your landing page| |BRAND_IMPRESSION_SHARE| Facilitate consumers' awareness of your brand| |ACQUIRE_NEW_CUSTOMERS| This property is a PREVIEW ONLY and cannot be used as part of a request or response, this note will be removed once supported. This goal drives new customer acquisition for your brands| |AD_VIEWS| This property is a PREVIEW ONLY and cannot be used as part of a request or response, this note will be removed once supported. This goal maximizes view for your ads|<br/>
type SbKeywordRecommendationGoal string

// List of SBKeywordRecommendationGoal
const (
	PAGE_VISIT_SbKeywordRecommendationGoal             SbKeywordRecommendationGoal = "PAGE_VISIT"
	BRAND_IMPRESSION_SHARE_SbKeywordRecommendationGoal SbKeywordRecommendationGoal = "BRAND_IMPRESSION_SHARE"
	ACQUIRE_NEW_CUSTOMERS_SbKeywordRecommendationGoal  SbKeywordRecommendationGoal = "ACQUIRE_NEW_CUSTOMERS"
	AD_VIEWS_SbKeywordRecommendationGoal               SbKeywordRecommendationGoal = "AD_VIEWS"
)
