/*
 * Amazon Ads API - Sponsored Brands
 *
 * Use the Amazon Ads API for Sponsored Brands for campaign, ad group, keyword, negative keyword, drafts, Stores, landing pages, and Brands management operations. For more information about Sponsored Brands, see the [Sponsored Brands Support Center](https://advertising.amazon.com/help#GQFZA83P55P747BZ). For onboarding information, see the [account setup](https://advertising.amazon.com/API/docs/v3/guides/account_setup) topic.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredbrandsv3

type SbCreateTargetingClauseRequest struct {
	// The identifier of an existing ad group. The newly created target is associated to this ad group.
	AdGroupId int64 `json:"adGroupId,omitempty"`
	// The identifier of an existing campaign. The newly created target is associated to this campaign.
	CampaignId  int64           `json:"campaignId,omitempty"`
	Expressions *[]SbExpression `json:"expressions,omitempty"`
	Bid         float64         `json:"bid,omitempty"`
}
