/*
 * Amazon Ads API - Sponsored Brands
 *
 * Use the Amazon Ads API for Sponsored Brands for campaign, ad group, keyword, negative keyword, drafts, Stores, landing pages, and Brands management operations. For more information about Sponsored Brands, see the [Sponsored Brands Support Center](https://advertising.amazon.com/help#GQFZA83P55P747BZ). For onboarding information, see the [account setup](https://advertising.amazon.com/API/docs/v3/guides/account_setup) topic.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredbrandsv3

type InlineResponse20017ViolatingTextContents struct {
	// The ad component that includes the text that violates the specified policy.
	ModeratedComponent string `json:"moderatedComponent,omitempty"`
	// The specific text reviewed during moderation.
	ReviewedText  string                             `json:"reviewedText,omitempty"`
	TextEvidences []InlineResponse20017TextEvidences `json:"textEvidences,omitempty"`
}
