/*
 * Amazon Ads API - Sponsored Brands
 *
 * Use the Amazon Ads API for Sponsored Brands for campaign, ad group, keyword, negative keyword, drafts, Stores, landing pages, and Brands management operations. For more information about Sponsored Brands, see the [Sponsored Brands Support Center](https://advertising.amazon.com/help#GQFZA83P55P747BZ). For onboarding information, see the [account setup](https://advertising.amazon.com/API/docs/v3/guides/account_setup) topic.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredbrandsv3

type RecommendationsBidsBody struct {
	// The identifier of the campaign for which bid recommendations are created.
	CampaignId int64 `json:"campaignId,omitempty"`
	// Sum of the sizes of (targets + keywords + themeTypes) arrays should be <= 100
	Targets [][]SbExpression `json:"targets,omitempty"`
	// Sum of the sizes of (targets + keywords + themeTypes) arrays should be <= 100
	Keywords []SbBidRecommendationKeyword `json:"keywords,omitempty"`
	AdFormat *AdFormat                    `json:"adFormat,omitempty"`
	// Optional. Support `CPC` (cost per click) and `VCPM` (cost per thousand viewable impressions). | costType | goal | Expected result | |----------|------|-----------------| | Empty | Empty | Recommendation will be generated for costType= `CPC` and goal=`PAGE_VISIT`. | Specified | Empty | It will return error and no recommendation will be generated. | Empty | Specified | It will use default costType based on goal selection. e.g. goal=`BRAND_IMPRESSION_SHARE` then it will use costType = `VCPM` to generate recommendation. | Specified | Specified | The recommendation will be based on selected goal and costType. If the mismatch then it will generate an error.
	CostType string `json:"costType,omitempty"`
	// Sum of the sizes of (targets + keywords + themeTypes) arrays should be <= 100
	ThemeTypes []string `json:"themeTypes,omitempty"`
	Goal       string   `json:"goal,omitempty"`
}
