/*
 * Amazon Ads API - Sponsored Brands
 *
 * Use the Amazon Ads API for Sponsored Brands for campaign, ad group, keyword, negative keyword, drafts, Stores, landing pages, and Brands management operations. For more information about Sponsored Brands, see the [Sponsored Brands Support Center](https://advertising.amazon.com/help#GQFZA83P55P747BZ). For onboarding information, see the [account setup](https://advertising.amazon.com/API/docs/v3/guides/account_setup) topic. 
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredbrandsv3

// Render one or more product images and product details.
type SbCollectionCreative struct {
	// The brand name.
	BrandName string `json:"brandName,omitempty"`
	// The identifier of the brand logo image from the Store assets library. See [listAssets](https://advertising.amazon.com/API/docs/v3/reference/SponsoredBrands/Stores) for more information. Note that for campaigns created in the Amazon Ads console prior to release of the Store assets library, responses will not include a value for the brandLogoAssetID field.
	BrandLogoAssetId string `json:"brandLogoAssetId,omitempty"`
	// The address of the hosted image.
	BrandLogoUrl string `json:"brandLogoUrl,omitempty"`
	// The headline text. Maximum length of the string is 50 characters for all marketplaces other than Japan, which has a maximum length of 35 characters.
	Headline string `json:"headline,omitempty"`
	// An array of ASINs associated with the creative. **Note** do not pass an empty array. This results in an error.
	Asins []string `json:"asins,omitempty"`
	// Note that this field is supported only in the US and UK marketplaces. Set to `true` to have Amazon show other products from your landing page in the advertisement if they are more relevant to the shopper's search. Set to `false` to use the ASINs specified in the `asins` field. Do not specify in unsupported marketplaces.
	ShouldOptimizeAsins bool `json:"shouldOptimizeAsins,omitempty"`
	// The identifier of the brand logo image from the Store assets library. See [listAssets](https://advertising.amazon.com/API/docs/v3/reference/SponsoredBrands/Stores) for more information. Note that for campaigns created in the Amazon Ads console prior to release of the Store assets library, responses will not include a value for the brandLogoAssetID field.
	BrandLogoAssetID string `json:"brandLogoAssetID,omitempty"`
}
