/*
 * Amazon Ads API - Sponsored Brands
 *
 * Use the Amazon Ads API for Sponsored Brands for campaign, ad group, keyword, negative keyword, drafts, Stores, landing pages, and Brands management operations. For more information about Sponsored Brands, see the [Sponsored Brands Support Center](https://advertising.amazon.com/help#GQFZA83P55P747BZ). For onboarding information, see the [account setup](https://advertising.amazon.com/API/docs/v3/guides/account_setup) topic.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredbrandsv3

type SbListCampaignsResponseCommon struct {
	// The campaign identifier.
	CampaignId int32 `json:"campaignId,omitempty"`
	// The name of the campaign. This name must be unique to the Amazon Ads account to which the campaign is associated. Maximum length of the string is 128 characters.
	Name string             `json:"name,omitempty"`
	Tags *map[string]string `json:"tags,omitempty"`
	// The budget amount associated with the campaign.
	Budget     float64     `json:"budget,omitempty"`
	BudgetType *BudgetType `json:"budgetType,omitempty"`
	// The YYYYMMDD start date for the campaign. If this field is not set to a value, the current date is used.
	StartDate string `json:"startDate,omitempty"`
	// The YYYYMMDD end date for the campaign. Must be greater than the value for `startDate`. If not specified, the campaign has no end date and runs continuously.
	EndDate string `json:"endDate,omitempty"`
	State   *State `json:"state,omitempty"`
	// |Value|Description| |-----|-----------| |asinNotBuyable| The associated ASIN cannot be purchased due to eligibility or availability.| |billingError| The billing information associated with the account requires correction.| |ended| The value specified in the `endDate` field is in the past.| |landingPageNotAvailable| The specified landing page is not available. This may be caused by an incorrect address or a landing page with less than three ASINs.| |outOfBudget| The campaign has run out of budget.| |paused|The campaign state is set to `paused`.| |pendingReview| A newly created campaign that has not passed moderation review. Note that moderation review may take up to 72 hours. |ready| The campaign is scheduled for a future date.| |rejected| The campaign failed moderation review.| |running| The campaign is enabled and serving.| |scheduled| A transitive state between `ready` and `running`, as child entities associated with the campaign move to a running state.| |terminated| The state of the campaign is set to `archived`.| <br/>
	ServingStatus string `json:"servingStatus,omitempty"`
	// The brand entity identifier. Note that this field is required for sellers. For more information, see the [Stores reference](https://advertising.amazon.com/API/docs/v2/reference/stores) or [Brands reference](https://advertising.amazon.com/API/docs/v3/reference/SponsoredBrands/Brands).
	BrandEntityId string `json:"brandEntityId,omitempty"`
	// The identifier of the portfolio to which the campaign is associated.
	PortfolioId int64                                          `json:"portfolioId,omitempty"`
	LandingPage *OneOfSbListCampaignsResponseCommonLandingPage `json:"landingPage,omitempty"`
}
