/*
 * Amazon Ads API - Sponsored Brands
 *
 * Use the Amazon Ads API for Sponsored Brands for campaign, ad group, keyword, negative keyword, drafts, Stores, landing pages, and Brands management operations. For more information about Sponsored Brands, see the [Sponsored Brands Support Center](https://advertising.amazon.com/help#GQFZA83P55P747BZ). For onboarding information, see the [account setup](https://advertising.amazon.com/API/docs/v3/guides/account_setup) topic. 
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredbrandsv3
import (
	"time"
)

type InlineResponse20017 struct {
	// The campaign identifier.
	CampaignId int64 `json:"campaignId,omitempty"`
	// The moderation status of the campaign. |Status|Description| |------|-----------| |APPROVED|Moderation for the campaign is complete.| |IN_PROGRESS|Moderation for the campaign is in progress. The expected date and time for completion are specfied in the `etaForModeration` field.| |REJECTED|The campaign has failed moderation. Specific information about the content that violated policy is available in `policyViolations`.|
	ModerationStatus string `json:"moderationStatus,omitempty"`
	// Expected date and time by which moderation will be complete. Note that this field is present in the response only when `moderationStatus` is set to `IN_PROGRESS`.
	EtaForModeration time.Time `json:"etaForModeration,omitempty"`
	// A list of policy violations for a campaign that has failed moderation. Note that this field is present in the response only when `moderationStatus` is set to `REJECTED`.
	PolicyViolations []InlineResponse20017PolicyViolations `json:"policyViolations,omitempty"`
}
