/*
 * Amazon Marketing Stream
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package marketingstream

// UpdateEntityStatus : Update the status of the entity
type UpdateEntityStatus string

// List of UpdateEntityStatus
const (
	ARCHIVED_UpdateEntityStatus UpdateEntityStatus = "ARCHIVED"
)
