/*
 * Product Selector
 *
 * The Amazon Product Selector API allows integrators to receive product metadata such as inventory status, price, eligibility status and product details for SKUS or ASINs in their Product Catalog in order to launch, manage or optimize Sponsored Product, Sponsored Brands or Sponsored Display advertising campaigns. The Product Selector API is available to Sellers, Vendors, and Authors. Note that for vendors it fetches inventory based on the vendor codes so the result could be different from elsewhere.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package productmetadata

// This denotes the fields related to [GlobalStore Program](https://sellercentral.amazon.com/help/hub/reference/external/202139180).
type ProductMetadataModelGlobalStoreSetting struct {
	// Country code of source marketplace where seller has listed the product. Possible source country codes include US, UK, DE, JP, and AE.
	CatalogSourceCountryCode string `json:"catalogSourceCountryCode,omitempty"`
}
