/*
 * PreModeration
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package premoderation

// Date component which needs to be pre moderated. Either startDate or endDate must be populated, or both can be populated.
type DateComponent struct {
	// Type of the date component.
	ComponentType string `json:"componentType"`
	// End date of the component in yyyy-MM-dd HH:mm:ss format
	EndDate string `json:"endDate,omitempty"`
	// Id of the component. The same will be returned as part of the response as well. This can be used to uniquely identify the component from the pre moderation response.
	Id string `json:"id"`
	// Start date of the component in yyyy-MM-dd HH:mm:ss format
	StartDate string `json:"startDate,omitempty"`
}
