/*
 * PreModeration
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package premoderation

type AsinPolicyViolation struct {
	// A policy violation code.
	Name string `json:"name,omitempty"`
	// A human-readable description of the policy.
	PolicyDescription string `json:"policyDescription,omitempty"`
	// Address of the policy documentation. Follow the link to learn more about the specified policy.
	PolicyLinkUrl string `json:"policyLinkUrl,omitempty"`
	// Type of policy violation.
	Type_ string `json:"type,omitempty"`
}
