/*
 * PreModeration
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package premoderation

// Structure of specification violation for a video component.
type VideoSpecViolation struct {
	// Structure of specifications for a video component, computed by moderation system, which violates the requirement in spec description
	ComputedViolations []VideoSpecComputed `json:"computedViolations,omitempty"`
	// A spec violation code.
	Name string `json:"name,omitempty"`
	// A human-readable description of the spec requirement.
	SpecDescription string `json:"specDescription,omitempty"`
	// Address of the ad specification documentation. Follow the link to learn more about the required ad specification.
	SpecLinkUrl string `json:"specLinkUrl,omitempty"`
	// Type of spec violation.
	Type_ string `json:"type,omitempty"`
}
