run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # 检查未处理的错误
    - gosimple      # 简化代码建议
    - govet         # 静态分析
    - ineffassign   # 检查无效赋值
    - staticcheck   # 静态检查
    - unused        # 检查未使用代码
    - gofmt         # 格式检查
    - goimports     # import 排序
    - misspell      # 拼写检查
    - revive        # 代码规范检查
    - bodyclose     # HTTP body 关闭检查
    - noctx         # HTTP 请求需要 context
    - gosec         # 安全检查

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"
  
  gosec:
    excludes:
      - G104  # 允许某些错误不处理（需谨慎）

issues:
  exclude-rules:
    # 测试文件允许更宽松的规则
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - bodyclose
        - noctx
    # 自动生成的代码允许更宽松的规则
    - path: pkg/adsapi/.*/(api_|model_|client\.go|response\.go)
      linters:
        - errcheck
        - gosec
        - bodyclose
        - noctx
  
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

