/*
 * Amazon Ads API for Data Providers.
 *
 * Use to create, read, or update audience metadata and to add or remove audience records. For onboarding information, see [_setting up for the Amazon Ads API_](../guides/onboarding/overview).
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dataprovider

// An object that contains user consent. Only one type of consent(TCF, GPP, amazonConsent) should be provided.
type V2dpaudienceConsent struct {
	// The type of consent provided.
	ConsentType string `json:"consentType,omitempty"`
	Tcf string `json:"tcf,omitempty"`
	Gpp string `json:"gpp,omitempty"`
	AmazonConsent *AmazonConsent `json:"amazonConsent,omitempty"`
}
