/*
 * Recommendations
 *
 * Sponsored Ad recommendations for Amazon Advertiser accounts.<table><tr><th>Recommendation_type</th><th>Description</th></tr><tr><td>NEW_CAMPAIGN</td><td>Create new campaigns to increase visibility</td></tr><tr><td>NEW_VIDEO_CAMPAIGN</td><td>Create new video campaigns to increase visibility</td></tr><tr><td>NEW_AD_GROUP</td><td>Create new ad groups to increase visibility</td></tr><tr><td>CAMPAIGN_BIDDING_STRATEGY</td><td>Update the bidding strategy to win at auction</td></tr><tr><td>CAMPAIGN_BUDGET</td><td>Update the campaign budget to remain active</td></tr><tr><td>CAMPAIGN_END_DATE</td><td>Update the end date of the campaign</td></tr><tr><td>CAMPAIGN_TOP_PLACEMENT</td><td>Make adjustments to compete for top of search placements</td></tr><tr><td>CAMPAIGN_PRODUCT_PLACEMENT</td><td>Make adjustments to compete for product page placements</td></tr><tr><td>CAMPAIGN_STATE</td><td>Update status of the campaign based on performance</td></tr><tr><td>NEW_CAMPAIGN_BIDDING_RULE</td><td>Create bidding rules for specific campaigns</td></tr><tr><td>CAMPAIGN_BIDDING_RULE</td><td>Update existing bidding rules</td></tr><tr><td>NEW_CAMPAIGN_BUDGET_RULE</td><td>Create new budget rules for holidays and sales events</td></tr><tr><td>CAMPAIGN_BUDGET_RULE</td><td>Update budget rules for holidays and sales events</td></tr><tr><td>AD_GROUP_STATE</td><td>Update status of the agroup based on performance</td></tr><tr><td>AD_GROUP_DEFAULT_BID</td><td>Update ad group bid values to win at auction</td></tr><tr><td>AD_GROUP_BID_OPTIMIZATION</td><td>Update ad group bid optimization strategy to improve engagement</td></tr><tr><td>NEW_KEYWORD</td><td>Create new keywords to increase visibility</td></tr><tr><td>KEYWORD_BID</td><td>Update bids for each keyword to win at auction</td></tr><tr><td>KEYWORD_STATE</td><td>Update status of keywords based on performance</td></tr><tr><td>NEW_NEGATIVE_KEYWORD</td><td>Create new negative keywords to reduce unwanted traffic</td></tr><tr><td>NEGATIVE_KEYWORD_STATE</td><td>Update status of negative keywords based on performance</td></tr><tr><td>NEW_PRODUCT_AD</td><td>Create new product ad to increase visibility</td></tr><tr><td>PRODUCT_AD_STATE</td><td>Update status of the product based on performance</td></tr><tr><td>NEW_PRODUCT_TARGETING</td><td>Create new product targets to increase visibility</td></tr><tr><td>PRODUCT_TARGETING_STATE</td><td>Update status of the product target based on performance</td></tr><tr><td>PRODUCT_TARGETING_BID</td><td>Update bids for each product target to win at auction</td></tr><tr><td>NEW_NEGATIVE_PRODUCT_TARGETING</td><td>Create new negative product targets to reduce unwanted traffic</td></tr><tr><td>NEGATIVE_PRODUCT_TARGETING_STATE</td><td>Update status of the negative product target based on performance</td></tr><tr><td>NEW_AUDIENCE_TARGETING</td><td>Create new audience targets to increase visibility</td></tr><tr><td>AUDIENCE_TARGETING_STATE</td><td>Update status of the audience target based on performance</td></tr><tr><td>AUDIENCE_TARGETING_BID</td><td>Update bids for each audience target to win at auction</td></tr><tr><td>NEW_NEGATIVE_AUDIENCE_TARGETING</td><td>Create new negative audience targets to reduce unwanted traffic</td></tr><tr><td>NEGATIVE_AUDIENCE_TARGETING_STATE</td><td>Update status of the negative audience target based on performance</td></tr></table>
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package tacticalrecommendations
// Locale : Eligible language codes.
type Locale string

// List of Locale
const (
	AR_AE_Locale Locale = "ar_AE"
	CS_CZ_Locale Locale = "cs_CZ"
	DE_DE_Locale Locale = "de_DE"
	EN_AE_Locale Locale = "en_AE"
	EN_AU_Locale Locale = "en_AU"
	EN_CA_Locale Locale = "en_CA"
	EN_GB_Locale Locale = "en_GB"
	EN_IN_Locale Locale = "en_IN"
	EN_SG_Locale Locale = "en_SG"
	EN_US_Locale Locale = "en_US"
	ES_CO_Locale Locale = "es_CO"
	ES_ES_Locale Locale = "es_ES"
	ES_MX_Locale Locale = "es_MX"
	ES_US_Locale Locale = "es_US"
	FR_CA_Locale Locale = "fr_CA"
	FR_FR_Locale Locale = "fr_FR"
	HE_IL_Locale Locale = "he_IL"
	HI_IN_Locale Locale = "hi_IN"
	IT_IT_Locale Locale = "it_IT"
	JA_JP_Locale Locale = "ja_JP"
	KO_KR_Locale Locale = "ko_KR"
	NL_NL_Locale Locale = "nl_NL"
	PL_PL_Locale Locale = "pl_PL"
	PT_BR_Locale Locale = "pt_BR"
	SV_SE_Locale Locale = "sv_SE"
	TA_IN_Locale Locale = "ta_IN"
	TH_TH_Locale Locale = "th_TH"
	TR_TR_Locale Locale = "tr_TR"
	VI_VN_Locale Locale = "vi_VN"
	ZH_CN_Locale Locale = "zh_CN"
	ZH_TW_Locale Locale = "zh_TW"
)
