/*
 * Recommendations
 *
 * Sponsored Ad recommendations for Amazon Advertiser accounts.<table><tr><th>Recommendation_type</th><th>Description</th></tr><tr><td>NEW_CAMPAIGN</td><td>Create new campaigns to increase visibility</td></tr><tr><td>NEW_VIDEO_CAMPAIGN</td><td>Create new video campaigns to increase visibility</td></tr><tr><td>NEW_AD_GROUP</td><td>Create new ad groups to increase visibility</td></tr><tr><td>CAMPAIGN_BIDDING_STRATEGY</td><td>Update the bidding strategy to win at auction</td></tr><tr><td>CAMPAIGN_BUDGET</td><td>Update the campaign budget to remain active</td></tr><tr><td>CAMPAIGN_END_DATE</td><td>Update the end date of the campaign</td></tr><tr><td>CAMPAIGN_TOP_PLACEMENT</td><td>Make adjustments to compete for top of search placements</td></tr><tr><td>CAMPAIGN_PRODUCT_PLACEMENT</td><td>Make adjustments to compete for product page placements</td></tr><tr><td>CAMPAIGN_STATE</td><td>Update status of the campaign based on performance</td></tr><tr><td>NEW_CAMPAIGN_BIDDING_RULE</td><td>Create bidding rules for specific campaigns</td></tr><tr><td>CAMPAIGN_BIDDING_RULE</td><td>Update existing bidding rules</td></tr><tr><td>NEW_CAMPAIGN_BUDGET_RULE</td><td>Create new budget rules for holidays and sales events</td></tr><tr><td>CAMPAIGN_BUDGET_RULE</td><td>Update budget rules for holidays and sales events</td></tr><tr><td>AD_GROUP_STATE</td><td>Update status of the agroup based on performance</td></tr><tr><td>AD_GROUP_DEFAULT_BID</td><td>Update ad group bid values to win at auction</td></tr><tr><td>AD_GROUP_BID_OPTIMIZATION</td><td>Update ad group bid optimization strategy to improve engagement</td></tr><tr><td>NEW_KEYWORD</td><td>Create new keywords to increase visibility</td></tr><tr><td>KEYWORD_BID</td><td>Update bids for each keyword to win at auction</td></tr><tr><td>KEYWORD_STATE</td><td>Update status of keywords based on performance</td></tr><tr><td>NEW_NEGATIVE_KEYWORD</td><td>Create new negative keywords to reduce unwanted traffic</td></tr><tr><td>NEGATIVE_KEYWORD_STATE</td><td>Update status of negative keywords based on performance</td></tr><tr><td>NEW_PRODUCT_AD</td><td>Create new product ad to increase visibility</td></tr><tr><td>PRODUCT_AD_STATE</td><td>Update status of the product based on performance</td></tr><tr><td>NEW_PRODUCT_TARGETING</td><td>Create new product targets to increase visibility</td></tr><tr><td>PRODUCT_TARGETING_STATE</td><td>Update status of the product target based on performance</td></tr><tr><td>PRODUCT_TARGETING_BID</td><td>Update bids for each product target to win at auction</td></tr><tr><td>NEW_NEGATIVE_PRODUCT_TARGETING</td><td>Create new negative product targets to reduce unwanted traffic</td></tr><tr><td>NEGATIVE_PRODUCT_TARGETING_STATE</td><td>Update status of the negative product target based on performance</td></tr><tr><td>NEW_AUDIENCE_TARGETING</td><td>Create new audience targets to increase visibility</td></tr><tr><td>AUDIENCE_TARGETING_STATE</td><td>Update status of the audience target based on performance</td></tr><tr><td>AUDIENCE_TARGETING_BID</td><td>Update bids for each audience target to win at auction</td></tr><tr><td>NEW_NEGATIVE_AUDIENCE_TARGETING</td><td>Create new negative audience targets to reduce unwanted traffic</td></tr><tr><td>NEGATIVE_AUDIENCE_TARGETING_STATE</td><td>Update status of the negative audience target based on performance</td></tr></table>
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package tacticalrecommendations

// RecommendationType : Type of recommendation to apply certain changes to the advertiser's sponsored ads.
type RecommendationType string

// List of RecommendationType
const (
	AD_GROUP_BID_OPTIMIZATION_RecommendationType         RecommendationType = "AD_GROUP_BID_OPTIMIZATION"
	AD_GROUP_DEFAULT_BID_RecommendationType              RecommendationType = "AD_GROUP_DEFAULT_BID"
	AD_GROUP_STATE_RecommendationType                    RecommendationType = "AD_GROUP_STATE"
	AUDIENCE_TARGETING_BID_RecommendationType            RecommendationType = "AUDIENCE_TARGETING_BID"
	AUDIENCE_TARGETING_STATE_RecommendationType          RecommendationType = "AUDIENCE_TARGETING_STATE"
	CAMPAIGN_BIDDING_RULE_RecommendationType             RecommendationType = "CAMPAIGN_BIDDING_RULE"
	CAMPAIGN_BIDDING_STRATEGY_RecommendationType         RecommendationType = "CAMPAIGN_BIDDING_STRATEGY"
	CAMPAIGN_BUDGET_RecommendationType                   RecommendationType = "CAMPAIGN_BUDGET"
	CAMPAIGN_BUDGET_RULE_RecommendationType              RecommendationType = "CAMPAIGN_BUDGET_RULE"
	CAMPAIGN_END_DATE_RecommendationType                 RecommendationType = "CAMPAIGN_END_DATE"
	CAMPAIGN_PRODUCT_PLACEMENT_RecommendationType        RecommendationType = "CAMPAIGN_PRODUCT_PLACEMENT"
	CAMPAIGN_STATE_RecommendationType                    RecommendationType = "CAMPAIGN_STATE"
	CAMPAIGN_TOP_PLACEMENT_RecommendationType            RecommendationType = "CAMPAIGN_TOP_PLACEMENT"
	KEYWORD_BID_RecommendationType                       RecommendationType = "KEYWORD_BID"
	KEYWORD_STATE_RecommendationType                     RecommendationType = "KEYWORD_STATE"
	NEGATIVE_AUDIENCE_TARGETING_STATE_RecommendationType RecommendationType = "NEGATIVE_AUDIENCE_TARGETING_STATE"
	NEGATIVE_KEYWORD_STATE_RecommendationType            RecommendationType = "NEGATIVE_KEYWORD_STATE"
	NEGATIVE_PRODUCT_TARGETING_STATE_RecommendationType  RecommendationType = "NEGATIVE_PRODUCT_TARGETING_STATE"
	NEW_AD_GROUP_RecommendationType                      RecommendationType = "NEW_AD_GROUP"
	NEW_AUDIENCE_TARGETING_RecommendationType            RecommendationType = "NEW_AUDIENCE_TARGETING"
	NEW_CAMPAIGN_RecommendationType                      RecommendationType = "NEW_CAMPAIGN"
	NEW_CAMPAIGN_BIDDING_RULE_RecommendationType         RecommendationType = "NEW_CAMPAIGN_BIDDING_RULE"
	NEW_CAMPAIGN_BUDGET_RULE_RecommendationType          RecommendationType = "NEW_CAMPAIGN_BUDGET_RULE"
	NEW_KEYWORD_RecommendationType                       RecommendationType = "NEW_KEYWORD"
	NEW_NEGATIVE_AUDIENCE_TARGETING_RecommendationType   RecommendationType = "NEW_NEGATIVE_AUDIENCE_TARGETING"
	NEW_NEGATIVE_KEYWORD_RecommendationType              RecommendationType = "NEW_NEGATIVE_KEYWORD"
	NEW_NEGATIVE_PRODUCT_TARGETING_RecommendationType    RecommendationType = "NEW_NEGATIVE_PRODUCT_TARGETING"
	NEW_PRODUCT_AD_RecommendationType                    RecommendationType = "NEW_PRODUCT_AD"
	NEW_PRODUCT_TARGETING_RecommendationType             RecommendationType = "NEW_PRODUCT_TARGETING"
	NEW_VIDEO_CAMPAIGN_RecommendationType                RecommendationType = "NEW_VIDEO_CAMPAIGN"
	PRODUCT_AD_STATE_RecommendationType                  RecommendationType = "PRODUCT_AD_STATE"
	PRODUCT_TARGETING_BID_RecommendationType             RecommendationType = "PRODUCT_TARGETING_BID"
	PRODUCT_TARGETING_STATE_RecommendationType           RecommendationType = "PRODUCT_TARGETING_STATE"
)
