/*
 * Advertisers
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package accountbudgets

// Request to update account budget feature flags information.
type UpdateAccountBudgetFeatureFlagsRequest struct {
	FeatureFlags *FeatureFlags `json:"featureFlags"`
}
