/*
 * Advertisers
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package accountbudgets

// The Error Response Object.
type AccountBudgetFeatureFlagsError struct {
	// An enumerated code for machine use.
	Code string `json:"code,omitempty"`
	// A human-readable description of the response.
	Details string `json:"details,omitempty"`
}
