/*
 * Portfolios
 *
 * This API allows users to do Portfolios management operations.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package portfoliosv2

type UpdatePortfolio struct {
	Budget *PortfolioBudget `json:"budget,omitempty"`
	BudgetControls *BudgetControls `json:"budgetControls,omitempty"`
	// The name of the portfolio.
	Name string `json:"name,omitempty"`
	// The ID of the portfolio.
	PortfolioId string `json:"portfolioId"`
	State *EntityState `json:"state,omitempty"`
}
