/*
 * Portfolios
 *
 * This API allows users to do Portfolios management operations.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package portfoliosv2

type Portfolio struct {
	Budget         *PortfolioBudget       `json:"budget,omitempty"`
	BudgetControls *BudgetControls        `json:"budgetControls,omitempty"`
	ExtendedData   *PortfolioExtendedData `json:"extendedData,omitempty"`
	// States if the portfolio is still within budget.
	InBudget bool `json:"inBudget,omitempty"`
	// The name of the portfolio.
	Name string `json:"name"`
	// The ID of the portfolio.
	PortfolioId string       `json:"portfolioId"`
	State       *EntityState `json:"state"`
}
