/*
 * Portfolios
 *
 * This API allows users to do Portfolios management operations.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package portfoliosv2
// CurrencyCode : The currency used for all monetary values for entities under this profile. Cannot be `null`. |Region|`countryCode`|Country Name|`currencyCode`| |-----|------|------|------| |NA|US|United States|USD| |NA|CA|Canada|CAD| |NA|MX|Mexico|MXN| |NA|BR|Brazil|BRL| |EU|UK|United Kingdom|GBP| |EU|DE|Germany|EUR| |EU|FR|France|EUR| |EU|ES|Spain|EUR| |EU|IT|Italy|EUR| |EU|NL|The Netherlands|EUR| |EU|SE|Sweden|SEK| |EU|PL|Poland|PLN| |EU|AE|United Arab Emirates|AED| |EU|TR|Turkey|TRY| |FE|JP|Japan|JPY| |FE|AU|Australia|AUD| |FE|SG|Singapore|SGD|
type CurrencyCode string

// List of CurrencyCode
const (
	AED_CurrencyCode CurrencyCode = "AED"
	AUD_CurrencyCode CurrencyCode = "AUD"
	BRL_CurrencyCode CurrencyCode = "BRL"
	CAD_CurrencyCode CurrencyCode = "CAD"
	CLP_CurrencyCode CurrencyCode = "CLP"
	CNY_CurrencyCode CurrencyCode = "CNY"
	COP_CurrencyCode CurrencyCode = "COP"
	EGP_CurrencyCode CurrencyCode = "EGP"
	EUR_CurrencyCode CurrencyCode = "EUR"
	GBP_CurrencyCode CurrencyCode = "GBP"
	INR_CurrencyCode CurrencyCode = "INR"
	JPY_CurrencyCode CurrencyCode = "JPY"
	MXN_CurrencyCode CurrencyCode = "MXN"
	NGN_CurrencyCode CurrencyCode = "NGN"
	PLN_CurrencyCode CurrencyCode = "PLN"
	SAR_CurrencyCode CurrencyCode = "SAR"
	SEK_CurrencyCode CurrencyCode = "SEK"
	SGD_CurrencyCode CurrencyCode = "SGD"
	TRY_CurrencyCode CurrencyCode = "TRY"
	USD_CurrencyCode CurrencyCode = "USD"
	ZAR_CurrencyCode CurrencyCode = "ZAR"
)
