/*
 * Portfolios
 *
 * This API allows users to do Portfolios management operations.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package portfoliosv2
import (
	"time"
)

type BudgetUsagePortfolio struct {
	// Budget amount of resource requested
	Budget float64 `json:"budget,omitempty"`
	// Budget usage percentage (spend / available budget) for the given budget policy.
	BudgetUsagePercent float64 `json:"budgetUsagePercent,omitempty"`
	// An index to maintain order of the portfolioIds
	Index float64 `json:"index,omitempty"`
	// ID of requested resource
	PortfolioId string `json:"portfolioId,omitempty"`
	// Last evaluation time for budget usage
	UsageUpdatedTimestamp time.Time `json:"usageUpdatedTimestamp,omitempty"`
}
