/*
 * Portfolios
 *
 * This API allows users to do Portfolios management operations.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package portfoliosv2

type BudgetUsagePortfolioBatchError struct {
	// An enumerated error code for machine use.
	Code string `json:"code,omitempty"`
	// A human-readable description of the response.
	Details string `json:"details,omitempty"`
	// An index to maintain order of the portfolioIds
	Index float64 `json:"index,omitempty"`
	// ID of requested resource
	PortfolioId string `json:"portfolioId,omitempty"`
}
