/*
 * AdvertisingTestAccount
 *
 * Create test advertising account for 3P API integrators
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testaccounts

// Error response object.
type ModelError struct {
	// The HTTP status code of the response.
	Code string `json:"code,omitempty"`
	// A human-readable description of the response.
	Details string `json:"details,omitempty"`
}
