/*
 * Advertising Accounts
 *
 * Public API for managing advertising accounts.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package advertisingaccounts

// Association can represent an Amazon Vendor, Seller or business who does not sell on Amazon
type Association struct {
	AmazonAuthor *AmazonAuthor `json:"amazonAuthor,omitempty"`
	AmazonSeller *AmazonSeller `json:"amazonSeller,omitempty"`
	AmazonVendor *AmazonVendor `json:"amazonVendor,omitempty"`
	Business     *Business     `json:"business,omitempty"`
}
