/*
 * Advertising Accounts
 *
 * Public API for managing advertising accounts.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package advertisingaccounts

type GetTermsTokenResponseContent struct {
	TermsTokenStatus *TermsTokenStatus `json:"termsTokenStatus"`
	TermsType *TermsType `json:"termsType,omitempty"`
}
