/*
 * Goal Seeking Bidder Target KPI Recommendation
 *
 * Creates a Target KPI recommendation for advertisers when they are in the process of creating a new campaign (ADSP).
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dsptargetkpi

// Nested object that contains the lower and upper bound of the recommendation range.
type RecommendedKpi struct {
	// Lower bound of recommendation range.
	LowerBound float64 `json:"lowerBound"`
	// Upper bound of recommendation range.
	UpperBound float64 `json:"upperBound"`
}
