/*
 * Amazon Ads API for Sponsored Display
 *
 * This API enables programmatic access for campaign creation, management, and reporting for Sponsored Display campaigns. For more information on the functionality, see the [Sponsored Display Support Center](https://advertising.amazon.com/help#GTPPHE6RAWC2C4LZ). For API onboarding information, see the [account setup](https://advertising.amazon.com/API/docs/en-us/guides/onboarding/overview) topic.<br/><br/> > This specification is available for download from the **[Advertising API developer portal](https://d3a0d0y2hgofx6.cloudfront.net/openapi/en-us/sponsored-display/3-0/openapi.yaml).**
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package profilesv3
import (
	"time"
)

// System generated Creative moderation.
type CreativeModeration struct {
	// Unique identifier of the creative.
	CreativeId float64 `json:"creativeId"`
	CreativeType *CreativeTypeInCreativeResponse `json:"creativeType"`
	// The moderation status of the creative. |Status|Description| |------|-----------| |APPROVED|Moderation for the creative is complete.| |IN_PROGRESS|Moderation for the creative is in progress. The expected date and time for completion are specfied in the `etaForModeration` field.| |REJECTED|The creative has failed moderation. Specific information about the content that violated policy is available in `policyViolations`.|
	ModerationStatus string `json:"moderationStatus"`
	// Expected date and time by which moderation will be complete.
	EtaForModeration time.Time `json:"etaForModeration"`
	// A list of policy violations for a creative that has failed moderation.
	PolicyViolations []CreativeModerationPolicyViolations `json:"policyViolations"`
}
