/*
 * Amazon Ads API for Sponsored Display
 *
 * This API enables programmatic access for campaign creation, management, and reporting for Sponsored Display campaigns. For more information on the functionality, see the [Sponsored Display Support Center](https://advertising.amazon.com/help#GTPPHE6RAWC2C4LZ). For API onboarding information, see the [account setup](https://advertising.amazon.com/API/docs/en-us/guides/onboarding/overview) topic.<br/><br/> > This specification is available for download from the **[Advertising API developer portal](https://d3a0d0y2hgofx6.cloudfront.net/openapi/en-us/sponsored-display/3-0/openapi.yaml).**
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package profilesv3

type Recurrence struct {
	Type_ *RecurrenceType `json:"type,omitempty"`
	// Object representing days of the week for weekly type rule. It is not required for daily recurrence type
	DaysOfWeek []DayOfWeek `json:"daysOfWeek,omitempty"`
	// List of objects representing start and end time of desired intra-day budget rule window
	IntraDaySchedule []TimeOfDay `json:"intraDaySchedule,omitempty"`
}
