/*
 * Amazon Ads API for Sponsored Display
 *
 * This API enables programmatic access for campaign creation, management, and reporting for Sponsored Display campaigns. For more information on the functionality, see the [Sponsored Display Support Center](https://advertising.amazon.com/help#GTPPHE6RAWC2C4LZ). For API onboarding information, see the [account setup](https://advertising.amazon.com/API/docs/en-us/guides/onboarding/overview) topic.<br/><br/> > This specification is available for download from the **[Advertising API developer portal](https://d3a0d0y2hgofx6.cloudfront.net/openapi/en-us/sponsored-display/3-0/openapi.yaml).**
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package profilesv3

// SdTargetingRecommendationsLocale : List of supported locales.
type SdTargetingRecommendationsLocale string

// List of SDTargetingRecommendationsLocale
const (
	AR_AE_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "ar_AE"
	DE_DE_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "de_DE"
	EN_AE_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "en_AE"
	EN_AU_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "en_AU"
	EN_CA_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "en_CA"
	EN_GB_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "en_GB"
	EN_IN_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "en_IN"
	EN_SG_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "en_SG"
	EN_US_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "en_US"
	ES_ES_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "es_ES"
	ES_MX_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "es_MX"
	FR_CA_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "fr_CA"
	FR_FR_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "fr_FR"
	HI_IN_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "hi_IN"
	IT_IT_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "it_IT"
	JA_JP_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "ja_JP"
	KO_KR_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "ko_KR"
	NL_NL_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "nl_NL"
	PL_PL_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "pl_PL"
	PT_BR_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "pt_BR"
	SV_SE_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "sv_SE"
	TA_IN_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "ta_IN"
	TH_TH_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "th_TH"
	TR_TR_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "tr_TR"
	VI_VN_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "vi_VN"
	ZH_CN_SdTargetingRecommendationsLocale SdTargetingRecommendationsLocale = "zh_CN"
)
