/*
 * Conversions API
 *
 * Conversion management.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dspconversions

type DeleteMobileMeasurementPartnerAppRegistrationV1 struct {
	MmpAppId string `json:"mmpAppId"`
}
