/*
 * Conversions API
 *
 * Conversion management.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dspconversions

type MobileMeasurementPartnerAppBatchResponseV1 struct {
	Error_  []MobileMeasurementPartnerErrorResponseV1   `json:"error,omitempty"`
	Success []MobileMeasurementPartnerSuccessResponseV1 `json:"success,omitempty"`
}
