/*
 * Conversions API
 *
 * Conversion management.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dspconversions

// All ConversionMatchKey objects for a single user should be grouped into a single EventDeletionRequest list.
type EventDeletionRequestV1 struct {
	MatchKeys []ConversionMatchKeyV1 `json:"matchKeys,omitempty"`
}
