/*
 * Brand Metrics
 *
 * Brand Metrics provides a new measurement solution that quantifies opportunities for your brand at each stage of the customer journey on Amazon, and helps brands understand the value of different shopping engagements that impact stages of that journey. You can now access Awareness and Consideration indices that compare your performance to peers using models predictive of consideration and sales. Brand Metrics quantifies the number of customers in the awareness and consideration marketing funnel stages and is built at scale to measure all shopping engagements with your brand on Amazon, not just ad-attributed engagements. Additionally, BM breaks out key shopping engagements at each stage of the shopping journey, along with the Return on Engagement, so you can measure the historical sales following a consideration event or purchase.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package brandmetrics

// Response object containing Brand Metrics Report metadata.
type BrandMetricsGenerateReportResponseV11 struct {
	// The expiration time of the URI in the location property in milliseconds. The expiration time is the interval between the time the response was generated and the time the URI expires.
	Expiration int64 `json:"expiration"`
	// Format of the report.
	Format string `json:"format"`
	// The URI address of the report.
	Location string `json:"location,omitempty"`
	// The identifier of the report.
	ReportId string `json:"reportId"`
	// The build status of the report.
	Status string `json:"status"`
	// A human-readable description of the current status.
	StatusDetails string `json:"statusDetails"`
}
