/*
 * Locations
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package locations

// Resulting locations will match all specified filters
type ListLocationsRequestBodyV1 struct {
	Filters []LocationFilterV1 `json:"filters,omitempty"`
}
