/*
 * Persona Builder API
 *
 * DSP Persona Builder API.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package personabuilder
import (
	"time"
)

type BandedSizeResponseContent struct {
	EstimatedSize *BandedSizeInsights `json:"estimatedSize"`
	// UTC timestamp in ISO 8601 format indicating when insight was last generated for the audience targeting expression.
	LastUpdatedAt time.Time `json:"lastUpdatedAt"`
}
