/*
 * Persona Builder API
 *
 * DSP Persona Builder API.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package personabuilder
import (
	"time"
)

type TopOverlappingAudiencesResponseContent struct {
	// Top audiences associated with customers in the input expression, ordered by the affinity score.                       Affinity is a measure of how likely customers in the input expression are to belong to a specific                     audience. An affinity of 5 for some audience indicates that customers in the input expression set                     are 5 times as likely to belong to this audience than the average of customers on Amazon.
	Audiences []AudienceInsight `json:"audiences"`
	// UTC timestamp in ISO 8601 format indicating when insight was last generated for the input audience set.
	LastUpdatedAt time.Time `json:"lastUpdatedAt"`
	// Optional: If present, there are more insights than initially returned. Use this token to call the operation again and have the additional insights returned. The token is valid for 8 hours from the initial request.
	NextToken string `json:"nextToken,omitempty"`
}
