/*
 * Amazon Advertiser API for Retail Ad Service
 *
 * The API that enables advertisers to run campaigns through Amazon Ads on retailers that are launched on Amazon Retail Ad Service
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package retailadservice

// Exception resulting in mutating ProductAd management entities
type Rasv1ProductAdMutationExceptionResponseContent struct {
	Code   *Rasv1InvalidArgumentErrorCode `json:"code"`
	Errors []Rasv1ProductAdMutationError  `json:"errors,omitempty"`
	// Human readable error message
	Message string `json:"message"`
}
