/*
 * Amazon Advertiser API for Retail Ad Service
 *
 * The API that enables advertisers to run campaigns through Amazon Ads on retailers that are launched on Amazon Retail Ad Service
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package retailadservice

type Rasv1TargetType string

// List of RASv1TargetType
const (
	AUTO_Rasv1TargetType Rasv1TargetType = "AUTO"
	KEYWORD_Rasv1TargetType Rasv1TargetType = "KEYWORD"
	PRODUCT_Rasv1TargetType Rasv1TargetType = "PRODUCT"
)
