/*
 * Amazon Advertiser API for Retail Ad Service
 *
 * The API that enables advertisers to run campaigns through Amazon Ads on retailers that are launched on Amazon Retail Ad Service
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package retailadservice

type Rasv1ListAdGroupsRequestContent struct {
	AdGroupIdFilter *Rasv1EntityIdFilter `json:"adGroupIdFilter,omitempty"`
	CampaignIdFilter *Rasv1ReducedEntityIdFilter `json:"campaignIdFilter,omitempty"`
	// Number of records to include in the paginated response. Defaults to max page size for given API
	MaxResults int32 `json:"maxResults,omitempty"`
	NameFilter *Rasv1NameFilter `json:"nameFilter,omitempty"`
	// token value allowing to navigate to the next response page
	NextToken string `json:"nextToken,omitempty"`
	StateFilter *Rasv1StateFilter `json:"stateFilter,omitempty"`
}
