/*
 * Amazon Advertiser API for Retail Ad Service
 *
 * The API that enables advertisers to run campaigns through Amazon Ads on retailers that are launched on Amazon Retail Ad Service
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package retailadservice

type Rasv1ProductIdType string

// List of RASv1ProductIdType
const (
	RETAILER_OFFER_Rasv1ProductIdType Rasv1ProductIdType = "RETAILER_OFFER"
)
