/*
 * Amazon Advertiser API for Retail Ad Service
 *
 * The API that enables advertisers to run campaigns through Amazon Ads on retailers that are launched on Amazon Retail Ad Service
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package retailadservice

type Rasv1CreateTargetInput struct {
	// The identifier of the ad group.
	AdGroupId string               `json:"adGroupId,omitempty"`
	Bid       *Rasv1TargetBidInput `json:"bid,omitempty"`
	// The identifier of the campaign.
	CampaignId string `json:"campaignId"`
	// Indicates whether the target is negative or not.
	Negative      bool                `json:"negative"`
	State         *Rasv1EntityState   `json:"state"`
	TargetDetails *Rasv1TargetDetails `json:"targetDetails"`
	TargetType    *Rasv1TargetType    `json:"targetType"`
}
