/*
 * Amazon Advertiser API for Retail Ad Service
 *
 * The API that enables advertisers to run campaigns through Amazon Ads on retailers that are launched on Amazon Retail Ad Service
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package retailadservice

type Rasv1MutateAdGroupFailureItem struct {
	// A list of validation errors
	Errors []Rasv1AdGroupMutationError `json:"errors,omitempty"`
	// The index of the AdGroup in the array from the request body
	Index int32 `json:"index"`
}
