/*
 * Amazon Advertiser API for Retail Ad Service
 *
 * The API that enables advertisers to run campaigns through Amazon Ads on retailers that are launched on Amazon Retail Ad Service
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package retailadservice

// Rasv1QueryTermMatchType : Match type for query filters. | Value |  Description | |-----------|------------| | `BROAD_MATCH` | Match if the queried value contains the filter value. (substring matching) | | `EXACT_MATCH` | Match if the queried value is exactly equivalent to the filter value. |
type Rasv1QueryTermMatchType string

// List of RASv1QueryTermMatchType
const (
	BROAD_MATCH_Rasv1QueryTermMatchType Rasv1QueryTermMatchType = "BROAD_MATCH"
	EXACT_MATCH_Rasv1QueryTermMatchType Rasv1QueryTermMatchType = "EXACT_MATCH"
)
