/*
 * Audiences
 *
 * Audience Discovery API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package audiencesdiscovery

// The error response object.
type AudienceErrorV1 struct {
	Errors []AudienceSubErrorV1 `json:"errors,omitempty"`
	// A human-readable description of the response.
	Message string `json:"message,omitempty"`
	// A value created by Amazon API Gateway that uniquely identifies your request.
	RequestId string `json:"requestId,omitempty"`
}
