/*
 * Audiences
 *
 * Audience Discovery API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package audiencesdiscovery
// Operator : For a given attributeType, operator used for attributeValues.
type Operator string

// List of Operator
const (
	ONE_OF_Operator Operator = "ONE_OF"
)
