/*
 * Audiences
 *
 * Audience Discovery API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package audiencesdiscovery

type FetchTaxonomyResponseV1 struct {
	Categories   []FetchTaxonomyNodeV1 `json:"categories,omitempty"`
	CategoryPath []string              `json:"categoryPath,omitempty"`
	NextToken    string                `json:"nextToken,omitempty"`
}
