/*
 * Audiences
 *
 * Audience Discovery API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package audiencesdiscovery

// Caller does not have permissions to edit specified audience.
type AudienceDeleteUnauthorizedExceptionResponseContent struct {
	ErrorResponse *DspAudienceDeleteResponse `json:"errorResponse"`
}
