/*
 * Audiences
 *
 * Audience Discovery API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package audiencesdiscovery

// The success response object.
type DspAudienceDeleteSuccessItem struct {
	// The audience identifier of the audience to be actioned.
	AudienceId string `json:"audienceId"`
	// unique request token for this request.
	IdempotencyKey string `json:"idempotencyKey"`
	// index of the DspAudienceEditRequestItem from the request. e.g. 1st item in the request will correspond to index 0 in the response.
	Index int32 `json:"index"`
}
