/*
 * Audiences
 *
 * Audience Discovery API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package audiencesdiscovery

type NotFoundErrorCode string

// List of NotFoundErrorCode
const (
	NOT_FOUND_NotFoundErrorCode NotFoundErrorCode = "NOT_FOUND"
)
