/*
 * Creative assets
 *
 * Use the creative assets API to create and manage video and image assets for use in Amazon Ads campaigns. For details on using this API, see [Creatives overview](guides/creative-asset/asset-library-overview).
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package creativeassets

type CaAssetStatus string

// List of caAssetStatus
const (
	ACTIVE_CaAssetStatus     CaAssetStatus = "ACTIVE"
	PROCESSING_CaAssetStatus CaAssetStatus = "PROCESSING"
	ARCHIVED_CaAssetStatus   CaAssetStatus = "ARCHIVED"
)
