/*
 * Creative assets
 *
 * Use the creative assets API to create and manage video and image assets for use in Amazon Ads campaigns. For details on using this API, see [Creatives overview](guides/creative-asset/asset-library-overview).
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package creativeassets

// This is used on registration of an asset, to associate DSP assets to a specific advertiser. This is **required** for assets being uploaded for use in DSP.
type CaRegistrationContext struct {
	AssociatedPrograms []CaAssociatedProgram `json:"associatedPrograms,omitempty"`
}
