/*
 * Sponsored Brands campaign management
 *
 * Create and manage Sponsored Brands campaigns.   To learn more about Sponsored Brands campaigns, see:   - [Sponsored Brands overview](guides/sponsored-brands/overview)  - [Sponsored Brands campaign structure](guides/sponsored-brands/campaigns/structure)  - [Get started with Sponsored Brands campaigns](guides/sponsored-brands/campaigns/get-started-with-campaigns)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredbrandsv4
// AssetSubType : Asset subtype from Asset Library which you are looking to get recommendations for. Asset Library documentation can be found here: https://advertising.amazon.com/API/docs/en-us/creative-asset-library
type AssetSubType string

// List of AssetSubType
const (
	CUSTOM_IMAGE_AssetSubType AssetSubType = "CUSTOM_IMAGE"
	LOGO_AssetSubType AssetSubType = "LOGO"
	PRODUCT_IMAGE_AssetSubType AssetSubType = "PRODUCT_IMAGE"
	AUTHOR_IMAGE_AssetSubType AssetSubType = "AUTHOR_IMAGE"
)
