/*
 * Sponsored Brands campaign management
 *
 * Create and manage Sponsored Brands campaigns.   To learn more about Sponsored Brands campaigns, see:   - [Sponsored Brands overview](guides/sponsored-brands/overview)  - [Sponsored Brands campaign structure](guides/sponsored-brands/campaigns/structure)  - [Get started with Sponsored Brands campaigns](guides/sponsored-brands/campaigns/get-started-with-campaigns)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredbrandsv4

type CreativeImageRecommendationEntry struct {
	// Recommendations with higher values are more relevant
	Score float64 `json:"score,omitempty"`
	// The asset size in bytes
	SizeInBytes float64 `json:"sizeInBytes,omitempty"`
	// The identifier of image/video asset from the store's asset library
	AssetId string `json:"assetId,omitempty"`
	// The URL of the asset
	ImageUrl string `json:"imageUrl,omitempty"`
	// The width of the asset in pixels
	Width float64 `json:"width,omitempty"`
	// The fileName of the asset
	Name string `json:"name,omitempty"`
	ContentType *MediaType `json:"contentType,omitempty"`
	// The height of the asset in pixels
	Height float64 `json:"height,omitempty"`
}
