/*
 * Sponsored Brands campaign management
 *
 * Create and manage Sponsored Brands campaigns.   To learn more about Sponsored Brands campaigns, see:   - [Sponsored Brands overview](guides/sponsored-brands/overview)  - [Sponsored Brands campaign structure](guides/sponsored-brands/campaigns/structure)  - [Get started with Sponsored Brands campaigns](guides/sponsored-brands/campaigns/get-started-with-campaigns)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredbrandsv4

// Category details.
type SbTargetingCategory struct {
	AsinCountRange *SbTargetingIntegerRange `json:"asinCountRange,omitempty"`
	// If the category is targetable or not.
	IsTargetable bool `json:"isTargetable,omitempty"`
	// The category refinement id of the parent category. Missing parentCategoryRefinementId signifies this is a root category.
	ParentCategoryRefinementId string                          `json:"parentCategoryRefinementId,omitempty"`
	EstimatedReach             *SbTargetingEstimatedReachRange `json:"estimatedReach,omitempty"`
	// Name of category.
	Name string `json:"name,omitempty"`
	// Translated name of the category.
	TranslatedName string `json:"translatedName,omitempty"`
	// The category refinement id. Please use /sb/targets/categories or /sb/recommendations/targets/category to retrieve category IDs.
	CategoryRefinementId string `json:"categoryRefinementId,omitempty"`
}
