/*
 * Sponsored Brands campaign management
 *
 * Create and manage Sponsored Brands campaigns.   To learn more about Sponsored Brands campaigns, see:   - [Sponsored Brands overview](guides/sponsored-brands/overview)  - [Sponsored Brands campaign structure](guides/sponsored-brands/campaigns/structure)  - [Get started with Sponsored Brands campaigns](guides/sponsored-brands/campaigns/get-started-with-campaigns)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredbrandsv4

// QueryTermMatchType : Defines how would the string resource field (e.g. campaign name, ad group name) be matched with the query term in filter.
type QueryTermMatchType string

// List of QueryTermMatchType
const (
	BROAD_MATCH_QueryTermMatchType QueryTermMatchType = "BROAD_MATCH"
	EXACT_MATCH_QueryTermMatchType QueryTermMatchType = "EXACT_MATCH"
)
