/*
 * Sponsored Brands campaign management
 *
 * Create and manage Sponsored Brands campaigns.   To learn more about Sponsored Brands campaigns, see:   - [Sponsored Brands overview](guides/sponsored-brands/overview)  - [Sponsored Brands campaign structure](guides/sponsored-brands/campaigns/structure)  - [Get started with Sponsored Brands campaigns](guides/sponsored-brands/campaigns/get-started-with-campaigns)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredbrandsv4

type ListCreativesRequestContent struct {
	// Filters creatives by optional creative type. By default, you can list all creative versions regardless of creative type.
	CreativeTypeFilter []CreativeType `json:"creativeTypeFilter,omitempty"`
	// The unique ID of a Sponsored Brands ad.
	AdId string `json:"adId"`
	// Operations that return paginated results include a pagination token in this field. To retrieve the next page of results, call the same operation and specify this token in the request. If the `NextToken` field is empty, there are no further results.
	NextToken string `json:"nextToken,omitempty"`
	// Set a limit on the number of results returned by an operation.
	MaxResults float64 `json:"maxResults,omitempty"`
	// Filters creatives by optional creative version. This means you can either list all creative versions without specific creative version filter, all just retrieve a single creative version by providing a specific version identifier.
	CreativeVersionFilter []string `json:"creativeVersionFilter,omitempty"`
	// Filters creatives by optional creative status. By default, you can list all creative versions regardless of creative status.
	CreativeStatusFilter []CreativeStatus `json:"creativeStatusFilter,omitempty"`
}
