/*
 * Sponsored Brands campaign management
 *
 * Create and manage Sponsored Brands campaigns.   To learn more about Sponsored Brands campaigns, see:   - [Sponsored Brands overview](guides/sponsored-brands/overview)  - [Sponsored Brands campaign structure](guides/sponsored-brands/campaigns/structure)  - [Get started with Sponsored Brands campaigns](guides/sponsored-brands/campaigns/get-started-with-campaigns)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredbrandsv4

// Placement : List of bid adjustments for placements. - HOME - The home page of the Amazon store. - DETAIL_PAGE - Product detail pages within the Amazon store. - OTHER - Other placement groups. Such as search pages in the Amazon Store. - TOP_OF_SEARCH - Top of search ads generally appear above the top search results.
type Placement string

// List of Placement
const (
	HOME_Placement          Placement = "HOME"
	DETAIL_PAGE_Placement   Placement = "DETAIL_PAGE"
	OTHER_Placement         Placement = "OTHER"
	TOP_OF_SEARCH_Placement Placement = "TOP_OF_SEARCH"
)
