/*
 * Sponsored Brands campaign management
 *
 * Create and manage Sponsored Brands campaigns.   To learn more about Sponsored Brands campaigns, see:   - [Sponsored Brands overview](guides/sponsored-brands/overview)  - [Sponsored Brands campaign structure](guides/sponsored-brands/campaigns/structure)  - [Get started with Sponsored Brands campaigns](guides/sponsored-brands/campaigns/get-started-with-campaigns)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredbrandsv4

type TextPosition struct {
	// Zero-based index into the text in reviewedText where the text specified in violatingText starts.
	Start int64 `json:"start,omitempty"`
	// Zero-based index into the text in reviewedText where the text specified in violatingText ends.
	End int64 `json:"end,omitempty"`
}
