/*
 * Sponsored Brands campaign management
 *
 * Create and manage Sponsored Brands campaigns.   To learn more about Sponsored Brands campaigns, see:   - [Sponsored Brands overview](guides/sponsored-brands/overview)  - [Sponsored Brands campaign structure](guides/sponsored-brands/campaigns/structure)  - [Get started with Sponsored Brands campaigns](guides/sponsored-brands/campaigns/get-started-with-campaigns)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredbrandsv4

// DayOfWeek : The day of the week.
type DayOfWeek string

// List of DayOfWeek
const (
	MONDAY_DayOfWeek    DayOfWeek = "MONDAY"
	TUESDAY_DayOfWeek   DayOfWeek = "TUESDAY"
	WEDNESDAY_DayOfWeek DayOfWeek = "WEDNESDAY"
	THURSDAY_DayOfWeek  DayOfWeek = "THURSDAY"
	FRIDAY_DayOfWeek    DayOfWeek = "FRIDAY"
	SATURDAY_DayOfWeek  DayOfWeek = "SATURDAY"
	SUNDAY_DayOfWeek    DayOfWeek = "SUNDAY"
)
