/*
 * Sponsored Brands campaign management
 *
 * Create and manage Sponsored Brands campaigns.   To learn more about Sponsored Brands campaigns, see:   - [Sponsored Brands overview](guides/sponsored-brands/overview)  - [Sponsored Brands campaign structure](guides/sponsored-brands/campaigns/structure)  - [Get started with Sponsored Brands campaigns](guides/sponsored-brands/campaigns/get-started-with-campaigns)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredbrandsv4

type BudgetUsageCampaignResponse struct {
	// List of budget usage percentages that were successfully pulled
	Success []BudgetUsageCampaign `json:"success,omitempty"`
	// List of budget usage percentages that failed to pull
	Error_ []BudgetUsageCampaignBatchError `json:"error,omitempty"`
}
