/*
 * Sponsored Brands campaign management
 *
 * Create and manage Sponsored Brands campaigns.   To learn more about Sponsored Brands campaigns, see:   - [Sponsored Brands overview](guides/sponsored-brands/overview)  - [Sponsored Brands campaign structure](guides/sponsored-brands/campaigns/structure)  - [Get started with Sponsored Brands campaigns](guides/sponsored-brands/campaigns/get-started-with-campaigns)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredbrandsv4

type CreativeImageRecommendationRequestContent struct {
	// ----------------------------------------------- List types ----------------------------------------------- A list of ASINs
	Asins        []string      `json:"asins"`
	AssetSubType *AssetSubType `json:"assetSubType,omitempty"`
	// Maximum number of recommendations that API should return. Response will [0, recommendations] recommendations (recommendations are not guaranteed).
	MaxNumRecommendations float64 `json:"maxNumRecommendations,omitempty"`
	// Filter assets by program types. For example, if only [A_PLUS] assets are requested then only assets that were used as A+ content will be recommended. If no program type is provided, recommend assets from all programs
	AssetPrograms []ProgramType `json:"assetPrograms,omitempty"`
	// (Optional) locale of creative headline and ASIN titles. If locale is not provided, default locale of marketplace is used. Currently, only en_US and en_CA are supported.
	Locale string `json:"locale,omitempty"`
	// The headline text. Maximum length of the string is 50 characters for all marketplaces other than Japan, which has a maximum length of 35 characters. See [the policy](https://advertising.amazon.com/resources/ad-policy/sponsored-ads-policies#headlines) for headline requirements.
	Headline string `json:"headline,omitempty"`
}
