/*
 * Sponsored Brands campaign management
 *
 * Create and manage Sponsored Brands campaigns.   To learn more about Sponsored Brands campaigns, see:   - [Sponsored Brands overview](guides/sponsored-brands/overview)  - [Sponsored Brands campaign structure](guides/sponsored-brands/campaigns/structure)  - [Get started with Sponsored Brands campaigns](guides/sponsored-brands/campaigns/get-started-with-campaigns)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredbrandsv4

type TimeOfDay struct {
	// The start time of intra-day budget rule window in the format 'hh:mm:ss' 
	StartTime string `json:"startTime,omitempty"`
	// The end time of intra-day budget rule window in the format 'hh:mm:ss'. Required to be greater than start-time. 
	EndTime string `json:"endTime,omitempty"`
}
