/*
 * Sponsored Brands campaign management
 *
 * Create and manage Sponsored Brands campaigns.   To learn more about Sponsored Brands campaigns, see:   - [Sponsored Brands overview](guides/sponsored-brands/overview)  - [Sponsored Brands campaign structure](guides/sponsored-brands/campaigns/structure)  - [Get started with Sponsored Brands campaigns](guides/sponsored-brands/campaigns/get-started-with-campaigns)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredbrandsv4

// Request structure of headline suggestion API.
type HeadlineSuggestionRequest struct {
	// An array of ASINs associated with the creative. Note do not pass an empty array, this results in an error. 
	Asins []string `json:"asins,omitempty"`
	// An array of Store Pages associated with SB Spotlight Creative.
	StorePages []StorePage `json:"storePages,omitempty"`
	// Maximum number of suggestions that API should return. Response will [0, maxNumSuggestions] suggestions (suggestions are not guaranteed).
	MaxNumSuggestions float64 `json:"maxNumSuggestions,omitempty"`
	AdFormat string `json:"adFormat,omitempty"`
}
