/*
 * Posts
 *
 * Posts API to manage Posts content.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package posts
// PostStatus : Status of Post:  * DRAFT - Post is in DRAFT state.  * REVIEW                - Post is in Review.  * LIVE - Post is live and available for Amazon Shoppers.                 * REJECTED - Post is Rejected. The detail of rejection is available in StatusMetadata.                 * WITHDRAWN - Post is Withdrawn from live.  * SCHEDULED - Post is scheduled                to go live.
type PostStatus string

// List of PostStatus
const (
	DRAFT_PostStatus PostStatus = "DRAFT"
	LIVE_PostStatus PostStatus = "LIVE"
	REJECTED_PostStatus PostStatus = "REJECTED"
	REVIEW_PostStatus PostStatus = "REVIEW"
	SCHEDULED_PostStatus PostStatus = "SCHEDULED"
	WITHDRAWN_PostStatus PostStatus = "WITHDRAWN"
)
