/*
 * Posts
 *
 * Posts API to manage Posts content.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package posts

// The criteria to determine how to sort a list of posts. Consists of the field to sort by, and the order.
type PostListSortCriterion struct {
	SortField *PostListSortField `json:"sortField,omitempty"`
	SortOrder *PostListSortOrder `json:"sortOrder,omitempty"`
}
