/*
 * Posts
 *
 * Posts API to manage Posts content.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package posts

// Returns the post created.
type CreatePostResponseContent struct {
	Post *Post `json:"post,omitempty"`
}
