/*
 * Stores
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package storesanalytics

// The filter to restrict the return data. Users can specifiy the pages/source/tags they feel interested in for the insights. The relationship between each field is 'AND'. E.g. The user can speficy {pageIds=[page1_id], sources=[source1]} to retrieve the related insights for page1 and source1. The user can specify {pageIds=[page1_id], tags=[tag1_name]} to retrieve related insights for page1 and tag1. <br><br> However, specifying both \"sources\" and \"tags\" is currently not supported. Users cannot retrieve insights for given sources and tags as all the tags belong to a specific source named \"tagged\".
type InsightFilter struct {
	// List of pages to be fetched for insight metrics. Users can first make request to the API with the same parameters but without the filter to retrieve all the available page ids.
	PageIds []string `json:"pageIds,omitempty"`
	// List of sources to be fetched for insight metrics.
	Sources []TrafficSource `json:"sources,omitempty"`
	// List of tags to be fetched for insight metrics. Users can first make request to the API with the same parameters but without the filter to retrieve all the available tag names.
	Tags []string `json:"tags,omitempty"`
}
