/*
 * Amazon Ads API for DSP
 *
 * Retrieve information of DSP advertisers.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dspadvertisers

// The DSP Advertiser object
type DspAdvertiserV1 struct {
	// The advertiser identifier.
	AdvertiserId string `json:"advertiserId,omitempty"`
	// The advertiser name.
	Name string `json:"name,omitempty"`
	Currency *DspSupportedCurrencyV1 `json:"currency,omitempty"`
	// The URL of the advertiser’s website.
	Url string `json:"url,omitempty"`
	Country *DspCountryV1 `json:"country,omitempty"`
	Timezone string `json:"timezone,omitempty"`
}
