/*
 * Change history
 *
 * Provides information about changes made to campaigns, adgroups, ads, etc
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package changehistory

type HistorySortParameter struct {
	Direction string `json:"direction,omitempty"`
	Key string `json:"key,omitempty"`
}
