/*
 * Eligibility
 *
 * Check advertising eligibility of global offers.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package producteligibility

// A request to evaluate account level eligibility for Amazon ad programs (Sponsored Products, Sponsored Brands, Sponsored Display, Stores, DirectToConsumer, Amazon Attribution, etc).
type ProgramEligibilityV2RequestContent struct {
	// Max results for pagination
	MaxResults float64 `json:"maxResults,omitempty"`
	// The pagination token that is required to go to the next page
	NextToken string `json:"nextToken,omitempty"`
}
