/*
 * Eligibility
 *
 * Check advertising eligibility of global offers.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package producteligibility

type ReasonItem struct {
	Code *ReasonCode `json:"code,omitempty"`
	// Message explaining what the status means. Example: Payment preference not found for associated billing account. Please add a new payment method
	Description string           `json:"description,omitempty"`
	Level       *IneligibleLevel `json:"level,omitempty"`
}
