/*
 * Eligibility
 *
 * Check advertising eligibility of global offers.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package producteligibility

// An Amazon product identifier, seller product identifier, or both.
type ProductDetails struct {
	// An Amazon product identifier.
	Asin string `json:"asin"`
	GlobalStoreSetting *GlobalStoreSetting `json:"globalStoreSetting,omitempty"`
	// A seller product identifier.
	Sku string `json:"sku,omitempty"`
}
