/*
 * Eligibility
 *
 * Check advertising eligibility of global offers.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package producteligibility

// An object of program eligibility responses for an advertiser.
type ProgramEligibilityResponseContent struct {
	EligibilityStatusMap *map[string]EligibilityStatusDetail `json:"eligibilityStatusMap,omitempty"`
}
