/*
 * Eligibility
 *
 * Check advertising eligibility of global offers.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package producteligibility

// AdProgram : This defines the AdPrograms supported
type AdProgram string

// List of AdProgram
const (
	DTC_AdProgram  AdProgram = "DTC"
	MAAS_AdProgram AdProgram = "MAAS"
	SB_AdProgram   AdProgram = "SB"
	SD_AdProgram   AdProgram = "SD"
	SPOT_AdProgram AdProgram = "SPOT"
)
