/*
 * Marketing Mix Modeling
 *
 * Request reports containing aggregated Amazon sales and media performance signals needed for marketing mix modeling (MMM).
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package marketingmixmodeling

// Only list brand groups with one of these ID values.
type Mmmv1brandGroupslistBrandGroupIdFilter struct {
	Include []string `json:"include"`
}
