/*
 * Marketing Mix Modeling
 *
 * Request reports containing aggregated Amazon sales and media performance signals needed for marketing mix modeling (MMM).
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package marketingmixmodeling

// The predefined brand or group of products being reported on.
type MmmBrandGroup struct {
	// Name of the advertiser associated with the brand group.
	AdvertiserName string `json:"advertiserName,omitempty"`
	// The unique identifier of the brand group.
	BrandGroupId string `json:"brandGroupId,omitempty"`
	// The display name of the brand group.
	BrandGroupName string `json:"brandGroupName,omitempty"`
	// The ISO 3166 country code of the marketplace associated with the brand group.
	CountryCode string `json:"countryCode,omitempty"`
}
