/*
 * Marketing Mix Modeling
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marketingmixmodeling

// Object is a generic map for unstructured data.
type Object map[string]interface{}
