/*
 * Advertising Billing
 *
 * APIs that enable integrators to manage different aspects of billing for their account like Addresses, Taxes, Payments, Invoices etc..
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package billing

// The input fails to satisfy the constraints specified by an Advertising API service.
type ValidationExceptionResponseContent struct {
	// Error Code.
	Code string `json:"code"`
	// Human readable response message.
	Message string `json:"message"`
}
