/*
 * Advertising Billing
 *
 * APIs that enable integrators to manage different aspects of billing for their account like Addresses, Taxes, Payments, Invoices etc..
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package billing

type CreateOrUpdateBillingProfilesResponseBillingProfilesSuccess struct {
	// Billing profile identifier corresponding to a billing profile in the list.
	BillingProfileId string `json:"billingProfileId,omitempty"`
	// Indicates the index of billing profile in the list of request payload.
	Index int64 `json:"index,omitempty"`
}
