/*
 * Advertising Billing
 *
 * APIs that enable integrators to manage different aspects of billing for their account like Addresses, Taxes, Payments, Invoices etc..
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package billing

// Represents a payment method.
type AdPaymentsPaymentMethod struct {
	// The processor used to execute payments on the card, such as Visa, MasterCard, etc. Only valued for credit card payment methods.
	Brand string `json:"brand,omitempty"`
	CountryCode *AdPaymentsCountryCode `json:"countryCode,omitempty"`
	ExpiryDetails *AdPaymentsExpiryDetails `json:"expiryDetails,omitempty"`
	ForeignExchange *AdPaymentsForeignExchange `json:"foreignExchange,omitempty"`
	// Identifies a credit card or direct debit payment method.
	InstrumentId string `json:"instrumentId,omitempty"`
	// A numerical priority assigned to each payment method within a given profile, dictating the sequential order in which these payment methods are utilized during payment execution. Lower numerical values indicate higher priority, with the option possessing the lowest value being selected first.
	Priority int32 `json:"priority"`
	// The seller account ID associated to this payment method, only valued for seller payable payment methods.
	SellerAccountId string `json:"sellerAccountId,omitempty"`
	// The last four digits of a credit card or bank account number.
	Tail string `json:"tail,omitempty"`
	Type_ *AdPaymentsPaymentMethodType `json:"type"`
	// The vendor code associated to this payment method, only valued for deduct from payment payment methods.
	VendorCode string `json:"vendorCode,omitempty"`
	VendorCodeBalance *AdPaymentsCurrencyAmount `json:"vendorCodeBalance,omitempty"`
	// The name of the vendor code this payment method represents.
	VendorCodeName string `json:"vendorCodeName,omitempty"`
}
