/*
 * Advertising Billing
 *
 * APIs that enable integrators to manage different aspects of billing for their account like Addresses, Taxes, Payments, Invoices etc..
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package billing

type IssuerTaxRegistrationInfo struct {
	// Tax registration with government (Ex: VAT ID, GST ID)
	TaxId string `json:"taxId"`
}
