/*
 * Advertising Billing
 *
 * APIs that enable integrators to manage different aspects of billing for their account like Addresses, Taxes, Payments, Invoices etc..
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package billing

// Foreign exchange information on credit card.
type AdPaymentsForeignExchange struct {
	CurrencyConversionConsentStatus *CurrencyConversionConsentStatus `json:"currencyConversionConsentStatus,omitempty"`
	// Percentage fee amazon is taking in transaction.
	FeePercentage float64 `json:"feePercentage,omitempty"`
	// Rate used for currency conversion.
	Rate float64 `json:"rate,omitempty"`
	// Currency the customer is paying in (credit card currency).
	TargetCurrencyCode string `json:"targetCurrencyCode,omitempty"`
}
