/*
 * Advertising Billing
 *
 * APIs that enable integrators to manage different aspects of billing for their account like Addresses, Taxes, Payments, Invoices etc..
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package billing

// AdPaymentsPaymentAgreementType : Enum defining different Payment Agreement types.
type AdPaymentsPaymentAgreementType string

// List of AdPaymentsPaymentAgreementType
const (
	AUTO_PAY_AdPaymentsPaymentAgreementType AdPaymentsPaymentAgreementType = "AUTO_PAY"
	PAY_NOW_AdPaymentsPaymentAgreementType  AdPaymentsPaymentAgreementType = "PAY_NOW"
)
