/*
 * Reach Planning Service
 *
 * Reach Planning Service API provides insight for advertising media planning by forecasting for reach, incremental/deduplicated reach, and other performance metrics.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package reachforecasting

type ListReachForecastTargetsV1RequestContent struct {
	// Number of records to include in the paginated response.
	MaxResults int32 `json:"maxResults,omitempty"`
	// Token value for navigating to the next response page.
	NextToken string `json:"nextToken,omitempty"`
	// This is the unique identifier of the Reach Forecast resource.
	ReachForecastId string `json:"reachForecastId"`
}
