/*
 * Reach Planning Service
 *
 * Reach Planning Service API provides insight for advertising media planning by forecasting for reach, incremental/deduplicated reach, and other performance metrics.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package reachforecasting

type UserLocationSignalV1 string

// List of UserLocationSignalV1
const (
	CURRENT_UserLocationSignalV1 UserLocationSignalV1 = "CURRENT"
	HOME_UserLocationSignalV1 UserLocationSignalV1 = "HOME"
	MULTIPLE_SIGNALS_UserLocationSignalV1 UserLocationSignalV1 = "MULTIPLE_SIGNALS"
)
