/*
 * Reach Planning Service
 *
 * Reach Planning Service API provides insight for advertising media planning by forecasting for reach, incremental/deduplicated reach, and other performance metrics.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package reachforecasting

import (
	"time"
)

// Performance curve for a specific metric
type GeneratePerformanceForecastV1ResponseElement struct {
	CountryCode *CountryCodeV1 `json:"countryCode"`
	// The date time that the performance forecast was created.
	CreationDateTime time.Time       `json:"creationDateTime"`
	CurrencyCode     *CurrencyCodeV1 `json:"currencyCode"`
	// List of data points for the curve
	DataPoints        []PerformanceCurveDataPointV1 `json:"dataPoints"`
	PerformanceMetric *PerformanceMetricV1          `json:"performanceMetric"`
}
