/*
 * Reach Planning Service
 *
 * Reach Planning Service API provides insight for advertising media planning by forecasting for reach, incremental/deduplicated reach, and other performance metrics.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package reachforecasting

type ProductCategoryTargetV1 struct {
	// The product category to target.
	AsinCategory string                       `json:"asinCategory"`
	TargetType   *ProductCategoryTargetTypeV1 `json:"targetType"`
}
