/*
 * Reach Planning Service
 *
 * Reach Planning Service API provides insight for advertising media planning by forecasting for reach, incremental/deduplicated reach, and other performance metrics.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package reachforecasting

type ReachCurveDataPointV1 struct {
	// The number of on-target impressions.
	Impressions int64 `json:"impressions"`
	// The forecasted on-target reached.
	Reach int64 `json:"reach"`
	// The forecasted spend in requested currency based on the estimated average CPM.
	Spend float64 `json:"spend"`
}
