/*
 * Reach Planning Service
 *
 * Reach Planning Service API provides insight for advertising media planning by forecasting for reach, incremental/deduplicated reach, and other performance metrics.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package reachforecasting

type ProductCategoryTargetTypeV1 string

// List of ProductCategoryTargetTypeV1
const (
	PRODUCT_CATEGORY_ProductCategoryTargetTypeV1 ProductCategoryTargetTypeV1 = "PRODUCT_CATEGORY"
)
