/*
 * Reach Planning Service
 *
 * Reach Planning Service API provides insight for advertising media planning by forecasting for reach, incremental/deduplicated reach, and other performance metrics.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package reachforecasting

type CreateDeduplicatedReachForecastsV1RequestElement struct {
	// The list of budget allocations for the Reach Forecasts to have their reach deduplicated. Total number of unique Reach Forecast IDs in budgetAllocations in the same request must be less than 100.
	BudgetAllocations []BudgetAllocationV1 `json:"budgetAllocations"`
}
