/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1

type CreateAdvertisedProducts struct {
	GlobalStoreSetting *CreateGlobalStoreSettings `json:"globalStoreSetting,omitempty"`
	// List of advertised product selectively applied at the given marketplace level
	MarketplaceSettings []CreateAdvertisedProductMarketplaceSetting `json:"marketplaceSettings,omitempty"`
	// The identifier of the advertised product.
	ProductId string `json:"productId,omitempty"`
	ProductIdType *ProductIdType `json:"productIdType"`
}
