/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1

// Target based on user application.
type CreateAppTarget struct {
	// The app identifier being targeted.
	AppId string `json:"appId,omitempty"`
	AppType *AppType `json:"appType,omitempty"`
}
