/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1

type CreateCampaignOptimizations struct {
	BidSettings    *CreateBidSettings    `json:"bidSettings,omitempty"`
	BudgetSettings *CreateBudgetSettings `json:"budgetSettings,omitempty"`
	GoalSettings   *CreateGoalSettings   `json:"goalSettings,omitempty"`
	// Primary inventory type of the campaign for filtering KPIs and recommending tactics.
	PrimaryInventoryTypes []PrimaryInventoryType `json:"primaryInventoryTypes,omitempty"`
}
