/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1

type MarketplaceAdFieldOverrides struct {
	State *State `json:"state,omitempty"`
	// Open ended labels with a key value pair applied to the ad
	Tags []Tag `json:"tags,omitempty"`
}
