/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1

// Targets ads in the specified content outstream position
type ContentOutstreamPositionTarget struct {
	OutstreamPosition *ContentOutstreamPosition `json:"outstreamPosition,omitempty"`
}
