/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1

// UpdateState : The user defined state for the resource. For ADSP, campaign and ad group resources can only be created in the PAUSED state and must be updated to ENABLED to activate for delivery | UpdateState | Description | | --- | --- | | `ENABLED` |  | | `PAUSED` |  |
type UpdateState string

// List of UpdateState
const (
	ENABLED_UpdateState UpdateState = "ENABLED"
	PAUSED_UpdateState  UpdateState = "PAUSED"
)
