/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1

type CreateLearnMoreVideoCallToActionSettings struct {
	// The url to drive users to learn more via the video CallToAction.
	Url string `json:"url,omitempty"`
}
