/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1
import (
	"time"
)

type Target struct {
	// A unique identifier for the ad group associated with the target. Only used for ad-group level targets.
	AdGroupId string `json:"adGroupId,omitempty"`
	AdProduct *AdProduct `json:"adProduct"`
	Bid *TargetBid `json:"bid,omitempty"`
	// A unique identifier for the campaign associated with the target. Only used for campaign-level targets.
	CampaignId string `json:"campaignId,omitempty"`
	// The date time the target was created.
	CreationDateTime time.Time `json:"creationDateTime"`
	// The date time the target was last updated.
	LastUpdatedDateTime time.Time `json:"lastUpdatedDateTime"`
	// List of marketplace-specific configurations for a global target that enables overriding certain attributes at individual marketplace level. For example, if a global target is ENABLED but needs to be PAUSED in DE marketplace, you can specify: [{marketplace: DE, overrides: {state: PAUSED}}]. When a marketplace-specific override is not provided, the target's global value is applied to that marketplace.
	MarketplaceConfigurations []MarketplaceTargetConfigurations `json:"marketplaceConfigurations,omitempty"`
	MarketplaceScope *MarketplaceScope `json:"marketplaceScope,omitempty"`
	// A list of country codes representing Amazon marketplaces | Marketplace | Description | | --- | --- | | `AE` |  | | `AU` |  | | `BE` |  | | `BR` |  | | `CA` |  | | `DE` |  | | `EG` |  | | `ES` |  | | `FR` |  | | `GB` |  | | `IN` |  | | `IT` |  | | `JP` |  | | `MX` |  | | `NL` |  | | `PL` |  | | `SA` |  | | `SE` |  | | `SG` |  | | `TR` |  | | `US` |  |
	Marketplaces []Marketplace `json:"marketplaces,omitempty"`
	// Indicates whether the target is negative or not.
	Negative bool `json:"negative"`
	State *State `json:"state"`
	Status *Status `json:"status,omitempty"`
	// Open ended labels with a key value pair applied to the target
	Tags []Tag `json:"tags,omitempty"`
	TargetDetails *TargetDetails `json:"targetDetails"`
	// A unique identifier for the target.
	TargetId string `json:"targetId"`
	TargetLevel *TargetLevel `json:"targetLevel,omitempty"`
	TargetType *TargetType `json:"targetType"`
}
