/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1

type ResponsiveEcommerceSettings struct {
	// The third party urls to trigger when an click is recorded.
	ClickTrackingUrls []CreativeTrackingUrl `json:"clickTrackingUrls,omitempty"`
	// The CreativeProperty Amazon will enhance or generate based on various factors like audience, placement etc.
	CreativePropertiesToOptimize []ResponsiveEcommerceCreativePropertiesToOptimize `json:"creativePropertiesToOptimize,omitempty"`
	// The placement sizes this creative should serve on.
	CreativeSizes []Size `json:"creativeSizes,omitempty"`
	// The disclaimer to use for the Responsive eCommerce experience.
	Disclaimers string `json:"disclaimers,omitempty"`
	// If set to true and the headline and/or video are not in the marketplace's default language, Amazon will attempt to translate them to the marketplace's default language. If Amazon is unable to translate them, the ad will be rejected by moderation.
	EnableCreativeAutoTranslation bool `json:"enableCreativeAutoTranslation,omitempty"`
	// The headline to use for the Responsive eCommerce experience.
	Headlines string `json:"headlines,omitempty"`
	// The image(s) to use.
	Images []Image `json:"images,omitempty"`
	// The third party urls to trigger when an impression is recorded.
	ImpressionTrackingUrls []CreativeTrackingUrl `json:"impressionTrackingUrls,omitempty"`
	// The inventory types this creative should serve on.
	InventoryTypes      []ComponentInventoryType        `json:"inventoryTypes,omitempty"`
	LandingPage         *ResponsiveEcommerceLandingPage `json:"landingPage,omitempty"`
	Language            *LanguageLocale                 `json:"language,omitempty"`
	Logos               *Image                          `json:"logos,omitempty"`
	ModerationStatus    *CreativeStatus                 `json:"moderationStatus,omitempty"`
	OptimizationGoalKpi *CreativeOptimizationGoalKpi    `json:"optimizationGoalKpi,omitempty"`
	// The products advertised for the Responsive eCommerce experience.
	Products []AdvertisedProducts `json:"products,omitempty"`
	// The rendering variations selected for the Responsive eCommerce experience.
	RecAdVariations            []ResponsiveEcommerceAdVariations `json:"recAdVariations,omitempty"`
	ResponsiveSizingBehavior   *ResponsiveSizingBehavior         `json:"responsiveSizingBehavior,omitempty"`
	SupportedThirdPartySellers *SupportedThirdPartySellers       `json:"supportedThirdPartySellers,omitempty"`
	// The headline entered by the advertiser.
	UntranslatedHeadlines string `json:"untranslatedHeadlines,omitempty"`
}
