/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1

type MarketplaceAdConfigurations struct {
	// Represents marketplace ad id (Ex: adId-US) associated to global ad (Ex: adId-Global)
	AdId string `json:"adId,omitempty"`
	Marketplace *Marketplace `json:"marketplace,omitempty"`
	Overrides *MarketplaceAdFieldOverrides `json:"overrides,omitempty"`
}
