/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1

type CreateProductCategoryRefinement struct {
	// The age range ID to target.
	ProductAgeRangeId string `json:"productAgeRangeId,omitempty"`
	// The resolved age range to target.
	ProductAgeRangeIdResolved string `json:"productAgeRangeIdResolved,omitempty"`
	// The brand ID to target.
	ProductBrandId string `json:"productBrandId,omitempty"`
	// The resolved name of the brand.
	ProductBrandIdResolved string `json:"productBrandIdResolved,omitempty"`
	// The product category ID to target.
	ProductCategoryId string `json:"productCategoryId,omitempty"`
	// The resolved product category.
	ProductCategoryIdResolved string `json:"productCategoryIdResolved,omitempty"`
	// The product genre ID to target.
	ProductGenreId string `json:"productGenreId,omitempty"`
	// Refinement to target products with a price greater than the value within the product category.
	ProductPriceGreaterThan float64 `json:"productPriceGreaterThan,omitempty"`
	// Refinement to target products with a price less than the value within the product category.
	ProductPriceLessThan float64 `json:"productPriceLessThan,omitempty"`
	// Target based on if a product is Prime-shipping eligible.
	ProductPrimeShippingEligible bool `json:"productPrimeShippingEligible,omitempty"`
	// Refinement to target products with a rating greater than the value within the product category.
	ProductRatingGreaterThan float64 `json:"productRatingGreaterThan,omitempty"`
	// Refinement to target products with a rating less than the value within the product category.
	ProductRatingLessThan float64 `json:"productRatingLessThan,omitempty"`
}
