/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1
// AdChoicesPosition : | AdChoicesPosition | Description | | --- | --- | | `BOTTOM_LEFT` |  | | `BOTTOM_RIGHT` |  | | `TOP_LEFT` |  | | `TOP_RIGHT` |  |
type AdChoicesPosition string

// List of AdChoicesPosition
const (
	BOTTOM_LEFT_AdChoicesPosition AdChoicesPosition = "BOTTOM_LEFT"
	BOTTOM_RIGHT_AdChoicesPosition AdChoicesPosition = "BOTTOM_RIGHT"
	TOP_LEFT_AdChoicesPosition AdChoicesPosition = "TOP_LEFT"
	TOP_RIGHT_AdChoicesPosition AdChoicesPosition = "TOP_RIGHT"
)
