/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1

// Targets a specific customer search term.
type ProductCategoryTarget struct {
	ProductCategoryRefinement *ProductCategoryRefinementValue `json:"productCategoryRefinement,omitempty"`
	ProductGenreRefinement    *ProductGenreRefinement         `json:"productGenreRefinement,omitempty"`
}
