/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1
// CostType : | CostType | Description | | --- | --- | | `CPC` | Cost per click. | | `VCPM` | Cost per thousand views. |
type CostType string

// List of CostType
const (
	CPC_CostType CostType = "CPC"
	VCPM_CostType CostType = "VCPM"
)
