/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1

type CreateDoubleVerifyAuthenticAttention struct {
	// One omni-channel segment that is informed by data from all DV campaigns to help avoid serving ads on generally poor performing apps and domains.
	UniversalAttention bool `json:"universalAttention,omitempty"`
}
