/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1

// FoldPosition : | FoldPosition | Description | | --- | --- | | `ABOVE_THE_FOLD` |  | | `BELOW_THE_FOLD` |  | | `UNKNOWN` |  |
type FoldPosition string

// List of FoldPosition
const (
	ABOVE_THE_FOLD_FoldPosition FoldPosition = "ABOVE_THE_FOLD"
	BELOW_THE_FOLD_FoldPosition FoldPosition = "BELOW_THE_FOLD"
	UNKNOWN_FoldPosition        FoldPosition = "UNKNOWN"
)
