/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1
// AverageCompletionAndFullyViewableRateTargetingType : The type of average completion and fully viewable rate targeting. | AverageCompletionAndFullyViewableRateTargetingType | Description | | --- | --- | | `ALLOW_ALL` |  | | `AVG_COMPLETION_FULLY_VIEWABLE_GTE_10` |  | | `AVG_COMPLETION_FULLY_VIEWABLE_GTE_20` |  | | `AVG_COMPLETION_FULLY_VIEWABLE_GTE_25` |  | | `AVG_COMPLETION_FULLY_VIEWABLE_GTE_30` |  | | `AVG_COMPLETION_FULLY_VIEWABLE_GTE_35` |  | | `AVG_COMPLETION_FULLY_VIEWABLE_GTE_40` |  |
type AverageCompletionAndFullyViewableRateTargetingType string

// List of AverageCompletionAndFullyViewableRateTargetingType
const (
	ALLOW_ALL_AverageCompletionAndFullyViewableRateTargetingType AverageCompletionAndFullyViewableRateTargetingType = "ALLOW_ALL"
	AVG_COMPLETION_FULLY_VIEWABLE_GTE_10_AverageCompletionAndFullyViewableRateTargetingType AverageCompletionAndFullyViewableRateTargetingType = "AVG_COMPLETION_FULLY_VIEWABLE_GTE_10"
	AVG_COMPLETION_FULLY_VIEWABLE_GTE_20_AverageCompletionAndFullyViewableRateTargetingType AverageCompletionAndFullyViewableRateTargetingType = "AVG_COMPLETION_FULLY_VIEWABLE_GTE_20"
	AVG_COMPLETION_FULLY_VIEWABLE_GTE_25_AverageCompletionAndFullyViewableRateTargetingType AverageCompletionAndFullyViewableRateTargetingType = "AVG_COMPLETION_FULLY_VIEWABLE_GTE_25"
	AVG_COMPLETION_FULLY_VIEWABLE_GTE_30_AverageCompletionAndFullyViewableRateTargetingType AverageCompletionAndFullyViewableRateTargetingType = "AVG_COMPLETION_FULLY_VIEWABLE_GTE_30"
	AVG_COMPLETION_FULLY_VIEWABLE_GTE_35_AverageCompletionAndFullyViewableRateTargetingType AverageCompletionAndFullyViewableRateTargetingType = "AVG_COMPLETION_FULLY_VIEWABLE_GTE_35"
	AVG_COMPLETION_FULLY_VIEWABLE_GTE_40_AverageCompletionAndFullyViewableRateTargetingType AverageCompletionAndFullyViewableRateTargetingType = "AVG_COMPLETION_FULLY_VIEWABLE_GTE_40"
)
