/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1

// AssetBasedCreativeCallToActionType : | AssetBasedCreativeCallToActionType | Description | | --- | --- | | `SHOP_NOW` |  | | `BUY_NOW` |  | | `PRE_ORDER_NOW` |  | | `LEARN_MORE` |  | | `SEE_DETAILS` |  | | `DISCOVER_MORE` |  | | `DOWNLOAD_NOW` |  | | `GET_APP` |  | | `SUBSCRIBE_NOW` |  | | `SIGN_UP_NOW` |  | | `BOOK_NOW` |  | | `EXPLORE_NOW` |  | | `GET_QUOTE` |  |
type AssetBasedCreativeCallToActionType string

// List of AssetBasedCreativeCallToActionType
const (
	BOOK_NOW_AssetBasedCreativeCallToActionType      AssetBasedCreativeCallToActionType = "BOOK_NOW"
	BUY_NOW_AssetBasedCreativeCallToActionType       AssetBasedCreativeCallToActionType = "BUY_NOW"
	DISCOVER_MORE_AssetBasedCreativeCallToActionType AssetBasedCreativeCallToActionType = "DISCOVER_MORE"
	DOWNLOAD_NOW_AssetBasedCreativeCallToActionType  AssetBasedCreativeCallToActionType = "DOWNLOAD_NOW"
	EXPLORE_NOW_AssetBasedCreativeCallToActionType   AssetBasedCreativeCallToActionType = "EXPLORE_NOW"
	GET_APP_AssetBasedCreativeCallToActionType       AssetBasedCreativeCallToActionType = "GET_APP"
	GET_QUOTE_AssetBasedCreativeCallToActionType     AssetBasedCreativeCallToActionType = "GET_QUOTE"
	LEARN_MORE_AssetBasedCreativeCallToActionType    AssetBasedCreativeCallToActionType = "LEARN_MORE"
	PRE_ORDER_NOW_AssetBasedCreativeCallToActionType AssetBasedCreativeCallToActionType = "PRE_ORDER_NOW"
	SEE_DETAILS_AssetBasedCreativeCallToActionType   AssetBasedCreativeCallToActionType = "SEE_DETAILS"
	SHOP_NOW_AssetBasedCreativeCallToActionType      AssetBasedCreativeCallToActionType = "SHOP_NOW"
	SIGN_UP_NOW_AssetBasedCreativeCallToActionType   AssetBasedCreativeCallToActionType = "SIGN_UP_NOW"
	SUBSCRIBE_NOW_AssetBasedCreativeCallToActionType AssetBasedCreativeCallToActionType = "SUBSCRIBE_NOW"
)
