/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1
// DvBrandSafetyAppAgeRatingType : | DVBrandSafetyAppAgeRatingType | Description | | --- | --- | | `EVERYONE_4_PLUS` |  | | `TWEENS_9_PLUS` |  | | `TEENS_12_PLUS` |  | | `MATURE_17_PLUS` |  | | `ADULTS_ONLY_18_PLUS` |  | | `UNKNOWN` |  |
type DvBrandSafetyAppAgeRatingType string

// List of DVBrandSafetyAppAgeRatingType
const (
	ADULTS_ONLY_18_PLUS_DvBrandSafetyAppAgeRatingType DvBrandSafetyAppAgeRatingType = "ADULTS_ONLY_18_PLUS"
	EVERYONE_4_PLUS_DvBrandSafetyAppAgeRatingType DvBrandSafetyAppAgeRatingType = "EVERYONE_4_PLUS"
	MATURE_17_PLUS_DvBrandSafetyAppAgeRatingType DvBrandSafetyAppAgeRatingType = "MATURE_17_PLUS"
	TEENS_12_PLUS_DvBrandSafetyAppAgeRatingType DvBrandSafetyAppAgeRatingType = "TEENS_12_PLUS"
	TWEENS_9_PLUS_DvBrandSafetyAppAgeRatingType DvBrandSafetyAppAgeRatingType = "TWEENS_9_PLUS"
	UNKNOWN_DvBrandSafetyAppAgeRatingType DvBrandSafetyAppAgeRatingType = "UNKNOWN"
)
