/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1

// Target based on geographic location.
type CreateLocationTarget struct {
	// The ID of the geographic location to target.
	LocationId string `json:"locationId,omitempty"`
	// A human-readable location text. It's a read-only field.
	LocationIdResolved string `json:"locationIdResolved,omitempty"`
}
