/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1

type CardCreativeElement struct {
	// The headline used for the card.
	Headline    string                     `json:"headline,omitempty"`
	LandingPage *StoreSpotlightLandingPage `json:"landingPage,omitempty"`
	Products    *AdvertisedProducts        `json:"products,omitempty"`
}
