/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1

type ContentTooLargeResponseContent struct {
	Code    *ErrorCode `json:"code"`
	Message string     `json:"message"`
}
