/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1

// Targets domains based on list inherited from the advertiser.
type CreateAdvertiserDomainList struct {
	// Set to TRUE to inherit domain list from advertiser.
	InheritFromAdvertiser bool `json:"inheritFromAdvertiser,omitempty"`
}
