/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1
// InventoryType : | InventoryType | Description | | --- | --- | | `STANDARD_DISPLAY` |  | | `AMAZON_MOBILE_DISPLAY` |  | | `AAP_MOBILE_APP` |  | | `DISPLAY` |  | | `VIDEO` |  | | `STREAMING_TV` |  | | `ONLINE_VIDEO` |  | | `AUDIO` | Audio ads that serve on streaming audio inventory. | | `PODCAST` | Podcast ads that serve on streaming podcast inventory. |
type InventoryType string

// List of InventoryType
const (
	AAP_MOBILE_APP_InventoryType InventoryType = "AAP_MOBILE_APP"
	AMAZON_MOBILE_DISPLAY_InventoryType InventoryType = "AMAZON_MOBILE_DISPLAY"
	AUDIO_InventoryType InventoryType = "AUDIO"
	DISPLAY_InventoryType InventoryType = "DISPLAY"
	ONLINE_VIDEO_InventoryType InventoryType = "ONLINE_VIDEO"
	PODCAST_InventoryType InventoryType = "PODCAST"
	STANDARD_DISPLAY_InventoryType InventoryType = "STANDARD_DISPLAY"
	STREAMING_TV_InventoryType InventoryType = "STREAMING_TV"
	VIDEO_InventoryType InventoryType = "VIDEO"
)
