/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1

type CreateVideoCreative struct {
	OnlineVideoSettings *CreateOnlineVideoSettings `json:"onlineVideoSettings,omitempty"`
	StreamingTvSettings *CreateStreamingTvSettings `json:"streamingTvSettings,omitempty"`
}
