/*
 * Amazon Ads API ALL
 *
 * Amazon Advertising API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package amazonadsv1

type FormatProperties struct {
	// Apply a boarder to the image to fit rules for some supplies.
	ApplyBorder bool `json:"applyBorder,omitempty"`
	// The height (in pixels) of the cropped image.
	Height int32 `json:"height,omitempty"`
	// The number of pixels from the left of the image where the crop should begin.
	Left int32 `json:"left,omitempty"`
	// The number of pixels from the top of the image where the crop should begin.
	Top int32 `json:"top,omitempty"`
	// The width (in pixels) of the cropped image.
	Width int32 `json:"width,omitempty"`
}
