/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type SponsoredProductsDuplicateValueErrorReason string

// List of SponsoredProductsDuplicateValueErrorReason
const (
	DUPLICATE_VALUE_SponsoredProductsDuplicateValueErrorReason SponsoredProductsDuplicateValueErrorReason = "DUPLICATE_VALUE"
	MARKETPLACE_ATTRIBUTES_REPEATED_SponsoredProductsDuplicateValueErrorReason SponsoredProductsDuplicateValueErrorReason = "MARKETPLACE_ATTRIBUTES_REPEATED"
	NAME_NOT_UNIQUE_SponsoredProductsDuplicateValueErrorReason SponsoredProductsDuplicateValueErrorReason = "NAME_NOT_UNIQUE"
)
