/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// A product target.
type SponsoredProductsCreateProductTarget struct {
	// Bid associated with the target. For more information about bid constraints by marketplace, see [bid limits](https://advertising.amazon.com/API/docs/en-us/concepts/limits#bid-constraints-by-marketplace).
	Bid float64 `json:"bid,omitempty"`
	MatchType *SponsoredProductsTargetingExpressionMatchType `json:"matchType"`
	// The product ASIN of the target.
	Target string `json:"target"`
}
