/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type SponsoredProductsProductAdMutationError struct {
	// The type of the error
	ErrorType string `json:"errorType"`
	ErrorValue *SponsoredProductsProductAdMutationErrorSelector `json:"errorValue"`
}
