/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// Keyword group. Represents a high level keyword targeting intent. e.g. the keyword group \"gift\" can target relevant search queries containing the word gift
type KeywordGroup struct {
	// Detailed Keyword group description.
	Description string `json:"description,omitempty"`
	// Unique Identifier for the keyword group. To be passed during targeting clause creation.
	Id string `json:"id"`
	// Summary of impacts.
	ImpactSummary string `json:"impactSummary,omitempty"`
	// Sample keywords that match the group.
	SampleKeywords []string `json:"sampleKeywords,omitempty"`
	// Keyword group text. Can be used for display purposes.
	Text string `json:"text"`
}
