/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type SponsoredProductsBulkKeywordOperationResponse struct {
	Error_ []SponsoredProductsKeywordFailureResponseItem `json:"error,omitempty"`
	Success []SponsoredProductsKeywordSuccessResponseItem `json:"success,omitempty"`
}
