/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// Unauthenticated. Request failed because user is not authenticated.
type SponsoredProductsUnauthenticatedExceptionResponseContent struct {
	Code *SponsoredProductsUnauthenticatedExceptionCode `json:"code,omitempty"`
	// A human-readable description of the response.
	Message string `json:"message,omitempty"`
}
