/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type GetTargetableAsinCountsRequest struct {
	AgeRanges *[]AgeRange `json:"ageRanges,omitempty"`
	Brands    *[]Brand    `json:"brands,omitempty"`
	// The category node id. Please use the GetTargetableCategories API or GetCategoryRecommendationsForASINs API to retrieve category IDs.
	Category string   `json:"category"`
	Genres   *[]Genre `json:"genres,omitempty"`
	// Indicates if products have prime shipping
	IsPrimeShipping bool         `json:"isPrimeShipping,omitempty"`
	PriceRange      *PriceRange  `json:"priceRange,omitempty"`
	RatingRange     *RatingRange `json:"ratingRange,omitempty"`
}
