/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type GetSpCampaignOptimizationRuleResponse struct {
	CampaignOptimizationRule *CampaignOptimizationRule `json:"CampaignOptimizationRule,omitempty"`
}
