/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type SponsoredProductsInvalidArgumentErrorCode string

// List of SponsoredProductsInvalidArgumentErrorCode
const (
	INVALID_ARGUMENT_SponsoredProductsInvalidArgumentErrorCode SponsoredProductsInvalidArgumentErrorCode = "INVALID_ARGUMENT"
)
