/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type Brand struct {
	// Id of brand. This field is REQUIRED if the Brand object is being used as an input. Use the GetRefinementsForCategory to retrieve Brand Node IDs.
	Id string `json:"id,omitempty"`
	// Name of brand. This field is OPTIONAL if the Brand object is being used as an input.
	Name string `json:"name,omitempty"`
}
