/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type BidAnalysesPerPlacement struct {
	ALL *[]BidAnalysis `json:"ALL"`
	PLACEMENT_PRODUCT_PAGE *[]BidAnalysis `json:"PLACEMENT_PRODUCT_PAGE"`
	PLACEMENT_REST_OF_SEARCH *[]BidAnalysis `json:"PLACEMENT_REST_OF_SEARCH"`
	PLACEMENT_TOP *[]BidAnalysis `json:"PLACEMENT_TOP"`
}
