/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// Filter entities by ExpressionType
type SponsoredProductsExpressionTypeFilter struct {
	Include []SponsoredProductsExpressionType `json:"include"`
}
