/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type SponsoredProductsBiddingErrorReason string

// List of SponsoredProductsBiddingErrorReason
const (
	AUDIENCES_MORE_THAN_ALLOWED_SponsoredProductsBiddingErrorReason       SponsoredProductsBiddingErrorReason = "BID_AUDIENCES_MORE_THAN_ALLOWED"
	GT_BUDGET_SponsoredProductsBiddingErrorReason                         SponsoredProductsBiddingErrorReason = "BID_GT_BUDGET"
	INVALID_AUDIENCE_ID_SponsoredProductsBiddingErrorReason               SponsoredProductsBiddingErrorReason = "BID_INVALID_AUDIENCE_ID"
	INVALID_AUDIENCE_SEGMENT_TYPE_SponsoredProductsBiddingErrorReason     SponsoredProductsBiddingErrorReason = "BID_INVALID_AUDIENCE_SEGMENT_TYPE"
	INVALID_PLACEMENT_SponsoredProductsBiddingErrorReason                 SponsoredProductsBiddingErrorReason = "BID_INVALID_PLACEMENT"
	INVALID_SHOPPER_COHORT_TYPE_SponsoredProductsBiddingErrorReason       SponsoredProductsBiddingErrorReason = "BID_INVALID_SHOPPER_COHORT_TYPE"
	MISSING_AUDIENCES_SponsoredProductsBiddingErrorReason                 SponsoredProductsBiddingErrorReason = "BID_MISSING_AUDIENCES"
	OUT_OF_MARKET_PLACE_RANGE_SponsoredProductsBiddingErrorReason         SponsoredProductsBiddingErrorReason = "BID_OUT_OF_MARKET_PLACE_RANGE"
	SHOPPER_COHORTS_MORE_THAN_ALLOWED_SponsoredProductsBiddingErrorReason SponsoredProductsBiddingErrorReason = "BID_SHOPPER_COHORTS_MORE_THAN_ALLOWED"
)
