/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type SponsoredProductsDuplicateValueError struct {
	Cause       *SponsoredProductsErrorCause  `json:"cause,omitempty"`
	Marketplace *SponsoredProductsMarketplace `json:"marketplace,omitempty"`
	// Human readable error message
	Message string                                      `json:"message"`
	Reason  *SponsoredProductsDuplicateValueErrorReason `json:"reason"`
}
