/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type OptimizationRulesApiSwaggerSearchOptimizationRulesResponse struct {
	// An enumerated error code for machine use.
	Code string `json:"code,omitempty"`
	NextToken string `json:"nextToken,omitempty"`
	OptimizationRules []OptimizationRulesApiSwaggerOptimizationRule `json:"optimizationRules,omitempty"`
}
