/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// Describes lower and upper bounds of the range. <br> Note: This object is nullable
type RangeMetricValue struct {
	Lower int32 `json:"lower,omitempty"`
	Upper int32 `json:"upper,omitempty"`
}
