/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type RuleRecommendation struct {
	CampaignId         string                     `json:"campaignId,omitempty"`
	PerformanceMetrics *RuleRecommendationMetrics `json:"performanceMetrics,omitempty"`
	// If true, performance metrics for the campaign are available in performanceMetrics response field.
	PerformanceMetricsExists bool `json:"performanceMetricsExists,omitempty"`
}
