/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type SponsoredProductsCampaign struct {
	Budget *SponsoredProductsBudget `json:"budget"`
	// The identifier of the campaign.
	CampaignId     string                           `json:"campaignId"`
	DynamicBidding *SponsoredProductsDynamicBidding `json:"dynamicBidding,omitempty"`
	// The format of the date is YYYY-MM-DD.
	EndDate      string                                 `json:"endDate,omitempty"`
	ExtendedData *SponsoredProductsCampaignExtendedData `json:"extendedData,omitempty"`
	// The name of the campaign.
	Name              string                              `json:"name"`
	OffAmazonSettings *SponsoredProductsOffAmazonSettings `json:"offAmazonSettings,omitempty"`
	// The identifier of an existing portfolio to which the campaign is associated.
	PortfolioId      string                             `json:"portfolioId,omitempty"`
	SiteRestrictions []SponsoredProductsSiteRestriction `json:"siteRestrictions,omitempty"`
	// The format of the date is YYYY-MM-DD.
	StartDate     string                          `json:"startDate"`
	State         *SponsoredProductsEntityState   `json:"state"`
	Tags          *map[string]string              `json:"tags,omitempty"`
	TargetingType *SponsoredProductsTargetingType `json:"targetingType"`
}
