/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// Recommended asins grouped by theme attribute.
type ThemeRecommendation struct {
	// A theme name representing the context around the recommended list of ASINs.
	Description string `json:"description,omitempty"`
	// List of recommended ASINs under current theme.
	RecommendedAsins []string `json:"recommendedAsins,omitempty"`
	// A theme name representing the context around the recommended list of ASINs.
	Theme string `json:"theme,omitempty"`
}
