/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// Request body for create campaign to optimization rules association. Maximum 100 rules can be associated to each campaign.
type OptimizationRulesApiSwaggerAssociateOptimizationRulesToCampaignRequest struct {
	// An array of rule identifiers.
	OptimizationRuleIds []string `json:"optimizationRuleIds"`
}
