/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// Request object for updating one or multiple optimization rules. Budget rules are not supported for this operation.
type OptimizationRulesApiSwaggerUpdateOptimizationRulesRequestV2 struct {
	OptimizationRules []OptimizationRulesApiSwaggerOptimizationRuleV2 `json:"optimizationRules"`
}
