/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type SponsoredProductsApplicableMarketplacesErrorReason string

// List of SponsoredProductsApplicableMarketplacesErrorReason
const (
	APPLICABLE_MARKETPLACES_MISMATCH_ERROR_SponsoredProductsApplicableMarketplacesErrorReason SponsoredProductsApplicableMarketplacesErrorReason = "APPLICABLE_MARKETPLACES_MISMATCH_ERROR"
)
