/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// The request object for creating a new target promotion group with new campaigns.
type SponsoredProductsNewCampaignDetails struct {
	Budget *SponsoredProductsNewCampaignBudget `json:"budget"`
	// The default bid value that gets applied if no bid is provided for the target. For more information about bid constraints by marketplace, see [bid limits](https://advertising.amazon.com/API/docs/en-us/concepts/limits#bid-constraints-by-marketplace).
	DefaultBid     float64                                     `json:"defaultBid"`
	DynamicBidding *SponsoredProductsNewCampaignDynamicBidding `json:"dynamicBidding,omitempty"`
	// The end date of the new target promotion group entities. The format of the date is YYYY-MM-DD.
	EndDate string `json:"endDate,omitempty"`
	// The name prefix to be used for the entities under the target promotion group. e.g. if the namePrefix     is ABC, we will create a keyword campaign with the name 'ABC-ManualKeywordTargeting-Campaign-AutoGenerated'
	NamePrefix string `json:"namePrefix"`
	// The start date of the new target promotion group entities. Default is today's date. The format of the date is YYYY-MM-DD.
	StartDate string             `json:"startDate,omitempty"`
	Tags      *map[string]string `json:"tags,omitempty"`
}
