/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// Filter entities by name
type SponsoredProductsNameFilter struct {
	Include            []string                             `json:"include,omitempty"`
	QueryTermMatchType *SponsoredProductsQueryTermMatchType `json:"queryTermMatchType,omitempty"`
}
