/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type SevenDaysEstimatedOpportunities struct {
	// End date of the opportunities date range in YYYY-MM-DDTHH:mm:ssZ format.
	EndDate string `json:"endDate,omitempty"`
	// Lower bound of the estimated incremental clicks that could be gained if all optimizations are made.
	EstimatedIncrementalClicksLower int32 `json:"estimatedIncrementalClicksLower,omitempty"`
	// Upper bound of the estimated incremental clicks that could be gained if all optimizations are made.
	EstimatedIncrementalClicksUpper int32 `json:"estimatedIncrementalClicksUpper,omitempty"`
	// Start date of the opportunities date range in YYYY-MM-DDTHH:mm:ssZ format.
	StartDate string `json:"startDate,omitempty"`
}
