/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type SponsoredProductsTargetingClause struct {
	// The identifier of the ad group to which this target is associated.
	AdGroupId string `json:"adGroupId"`
	// The bid for ads sourced using the target. Targets that do not have bid values in listTargetingClauses will inherit the defaultBid from the adGroup level. For more information about bid constraints by marketplace, see [bid limits](https://advertising.amazon.com/API/docs/en-us/concepts/limits#bid-constraints-by-marketplace).
	Bid float64 `json:"bid,omitempty"`
	// The identifier of the campaign to which this target is associated.
	CampaignId string `json:"campaignId"`
	// The targeting expression.
	Expression []SponsoredProductsTargetingExpressionPredicate `json:"expression"`
	ExpressionType *SponsoredProductsExpressionType `json:"expressionType"`
	ExtendedData *SponsoredProductsTargetingClauseExtendedData `json:"extendedData,omitempty"`
	// The resolved targeting expression.
	ResolvedExpression []SponsoredProductsTargetingExpressionPredicate `json:"resolvedExpression"`
	State *SponsoredProductsEntityState `json:"state"`
	// The target identifier
	TargetId string `json:"targetId"`
}
