/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// The impact metrics are given in the same order of suggested bids. <br> Note: This object is nullable
type ImpactMetric struct {
	Values []RangeMetricValue `json:"values,omitempty"`
}
