/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type SponsoredProductsTargetingClauseSetupErrorReason string

// List of SponsoredProductsTargetingClauseSetupErrorReason
const (
	AUTO_TARGETING_CLAUSE_CANNOT_BE_CREATED_MANUALLY_SponsoredProductsTargetingClauseSetupErrorReason       SponsoredProductsTargetingClauseSetupErrorReason = "AUTO_TARGETING_CLAUSE_CANNOT_BE_CREATED_MANUALLY"
	TARGETING_EXPRESSION_INVALID_VALUE_SponsoredProductsTargetingClauseSetupErrorReason                     SponsoredProductsTargetingClauseSetupErrorReason = "TARGETING_EXPRESSION_INVALID_VALUE"
	TARGETING_TYPE_NOT_ALLOWED_FOR_AUTO_TARGETING_CAMPAIGN_SponsoredProductsTargetingClauseSetupErrorReason SponsoredProductsTargetingClauseSetupErrorReason = "TARGETING_TYPE_NOT_ALLOWED_FOR_AUTO_TARGETING_CAMPAIGN"
	TYPE_CONFLICT_IN_AD_GROUP_SponsoredProductsTargetingClauseSetupErrorReason                              SponsoredProductsTargetingClauseSetupErrorReason = "TYPE_CONFLICT_IN_AD_GROUP"
)
