/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// OptimizationRulesApiSwaggerRuleCategoryV2 : The type of the optimization rule.
type OptimizationRulesApiSwaggerRuleCategoryV2 string

// List of OptimizationRulesAPISwaggerRuleCategoryV2
const (
	BID_OptimizationRulesApiSwaggerRuleCategoryV2       OptimizationRulesApiSwaggerRuleCategoryV2 = "BID"
	BUDGET_OptimizationRulesApiSwaggerRuleCategoryV2    OptimizationRulesApiSwaggerRuleCategoryV2 = "BUDGET"
	TARGETING_OptimizationRulesApiSwaggerRuleCategoryV2 OptimizationRulesApiSwaggerRuleCategoryV2 = "TARGETING"
)
