/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type SponsoredProductsAdEligibilityErrorReason string

// List of SponsoredProductsAdEligibilityErrorReason
const (
	AD_INELIGIBLE_SponsoredProductsAdEligibilityErrorReason SponsoredProductsAdEligibilityErrorReason = "AD_INELIGIBLE"
)
