/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type Recurrence struct {
	// Object representing days of the week for weekly type rule. It is not required for daily recurrence type
	DaysOfWeek []DayOfWeek `json:"daysOfWeek,omitempty"`
	// List of objects representing start and end time of desired intra-day budget rule window
	IntraDaySchedule []TimeOfDay `json:"intraDaySchedule,omitempty"`
	Type_ *RecurrenceType `json:"type,omitempty"`
}
