/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type BudgetRuleRecommendation struct {
	// rule id for the recomemendation
	RuleId string `json:"ruleId,omitempty"`
	// rule name for the recomemendation
	RuleName string `json:"ruleName,omitempty"`
	// suggested increase percent
	SuggestedBudgetIncreasePercent float64 `json:"suggestedBudgetIncreasePercent,omitempty"`
}
