/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type SpecialEvent struct {
	Benchmark *Benchmark `json:"benchmark,omitempty"`
	// Deprecated. The factor used to boost the recommended budget.
	BudgetModifier float64 `json:"budgetModifier,omitempty"`
	// Recommended daily budget for the new campaign during the special event period.
	DailyBudget float64 `json:"dailyBudget,omitempty"`
	// The end date of the special event in YYYYMMDD format.
	EndDate string `json:"endDate,omitempty"`
	// The key of the special event.
	EventKey string `json:"eventKey,omitempty"`
	// The name of the special event.
	EventName string `json:"eventName,omitempty"`
	// The start date of the special event in YYYYMMDD format.
	StartDate string `json:"startDate,omitempty"`
}
