/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// A list of bid recommendation themes and associated bid recommendations.
type ThemeBasedBidRecommendationResponseV5 struct {
	BidRecommendations []ThemeBasedBidRecommendationV5 `json:"bidRecommendations"`
}
