/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type MultiCountryBidRecommendationPerTargetingExpression struct {
	CountrySuggestedBids map[string][]float64 `json:"countrySuggestedBids"`
	Expression *MultiCountryTargetingExpression `json:"expression"`
}
