/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// BiddingStrategy : The bidding strategy selected for the campaign. Use `LEGACY_FOR_SALES` to lower your bid in real time when your ad may be less likely to convert to a sale. Use `AUTO_FOR_SALES` to increase your bid in real time when your ad may be more likely to convert to a sale or lower your bid when less likely to convert to a sale. Use `MANUAL` to use your exact bid along with any manual adjustments.
type BiddingStrategy string

// List of BiddingStrategy
const (
	AUTO_FOR_SALES_BiddingStrategy   BiddingStrategy = "AUTO_FOR_SALES"
	LEGACY_FOR_SALES_BiddingStrategy BiddingStrategy = "LEGACY_FOR_SALES"
	MANUAL_BiddingStrategy           BiddingStrategy = "MANUAL"
	RULE_BASED_BiddingStrategy       BiddingStrategy = "RULE_BASED"
)
