/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type SponsoredProductsCampaignMutationSuccessResponseItem struct {
	Campaign *SponsoredProductsCampaign `json:"campaign,omitempty"`
	// the campaign ID
	CampaignId string `json:"campaignId,omitempty"`
	// the index of the campaign in the array from the request body
	Index int32 `json:"index"`
}
