/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3
// SponsoredProductsTargetType : Indicates if the recommendation target is a Keyword or ASIN
type SponsoredProductsTargetType string

// List of SponsoredProductsTargetType
const (
	ASIN_SponsoredProductsTargetType SponsoredProductsTargetType = "ASIN"
	KEYWORD_SponsoredProductsTargetType SponsoredProductsTargetType = "KEYWORD"
)
