/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type SponsoredProductsTargetingClauseSuccessResponseItem struct {
	// the index of the targetingClause in the array from the request body
	Index int32 `json:"index"`
	// the targetingClause ID
	TargetId string `json:"targetId,omitempty"`
	TargetingClause *SponsoredProductsTargetingClause `json:"targetingClause,omitempty"`
}
