/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// Errors related to range constraints violations
type SponsoredProductsRangeError struct {
	// allowed values
	Allowed []string `json:"allowed,omitempty"`
	Cause *SponsoredProductsErrorCause `json:"cause,omitempty"`
	// optional lower limit
	LowerLimit string `json:"lowerLimit,omitempty"`
	Marketplace *SponsoredProductsMarketplace `json:"marketplace,omitempty"`
	// Human readable error message
	Message string `json:"message"`
	Reason *SponsoredProductsValueLimitErrorReason `json:"reason"`
	// optional upper limit
	UpperLimit string `json:"upperLimit,omitempty"`
}
