/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// The product placement.
type SponsoredProductsNewCampaignPlacementBidding struct {
	// The bidding placement percentage.
	Percentage int32 `json:"percentage"`
	// The bidding placement. One of PLACEMENT_TOP, PLACEMENT_PRODUCT_PAGE, PLACEMENT_REST_OF_SEARCH.
	Placement string `json:"placement"`
}
