/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// Error that represents non-retryable API service error. Sending the same request will result in another error.
type SponsoredProductsInternalServerError struct {
	Cause *SponsoredProductsErrorCause `json:"cause,omitempty"`
	// Human readable error message
	Message string                                      `json:"message"`
	Reason  *SponsoredProductsInternalServerErrorReason `json:"reason"`
}
