/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type MultiCountryBidRecommendationError struct {
	// Machine readable error code.
	Code string `json:"code,omitempty"`
	// Countries where error have occurred
	CountryCodes []string `json:"countryCodes,omitempty"`
	// Human readable 1 liner error message
	Message string `json:"message,omitempty"`
}
