/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3
// RuleState : The campaign optimization rule state.
type RuleState string

// List of RuleState
const (
	DISABLED_RuleState RuleState = "DISABLED"
	ENABLED_RuleState RuleState = "ENABLED"
)
