/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type SponsoredProductsAsinOwnershipErrorReason string

// List of SponsoredProductsAsinOwnershipErrorReason
const (
	ASIN_NOT_OWNED_BY_AUTHOR_SponsoredProductsAsinOwnershipErrorReason SponsoredProductsAsinOwnershipErrorReason = "ASIN_NOT_OWNED_BY_AUTHOR"
)
