/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// Exception resulting in mutating campaign management entities
type SponsoredProductsCampaignMutationExceptionResponseContent struct {
	Code   *SponsoredProductsInvalidArgumentErrorCode `json:"code"`
	Errors []SponsoredProductsCampaignMutationError   `json:"errors,omitempty"`
	// Human readable error message
	Message string `json:"message"`
}
