/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type SponsoredProductsBulkTargetingClauseOperationResponse struct {
	Error_  []SponsoredProductsTargetingClauseFailureResponseItem `json:"error,omitempty"`
	Success []SponsoredProductsTargetingClauseSuccessResponseItem `json:"success,omitempty"`
}
