/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// SponsoredProductsQueryTermMatchType : Match type for query filters. | Value |  Description | |-----------|------------| | `BROAD_MATCH` | Match if the queried value contains the filter value (substring matching). Note: If queryTermMatchType is set to BROAD_MATCH, only matches for the first query included will be returned. | | `EXACT_MATCH` | Match if the queried value is exactly equivalent to the filter value. |
type SponsoredProductsQueryTermMatchType string

// List of SponsoredProductsQueryTermMatchType
const (
	BROAD_MATCH_SponsoredProductsQueryTermMatchType SponsoredProductsQueryTermMatchType = "BROAD_MATCH"
	EXACT_MATCH_SponsoredProductsQueryTermMatchType SponsoredProductsQueryTermMatchType = "EXACT_MATCH"
)
