/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type SponsoredProductsBillingErrorReason string

// List of SponsoredProductsBillingErrorReason
const (
	ADVERTISER_BILLING_SETUP_INCOMPLETE_SponsoredProductsBillingErrorReason SponsoredProductsBillingErrorReason = "ADVERTISER_BILLING_SETUP_INCOMPLETE"
	ADVERTISER_SUSPENDED_SponsoredProductsBillingErrorReason                SponsoredProductsBillingErrorReason = "ADVERTISER_SUSPENDED"
	BILLING_ACCOUNT_NOT_FOUND_SponsoredProductsBillingErrorReason           SponsoredProductsBillingErrorReason = "BILLING_ACCOUNT_NOT_FOUND"
	EXPIRED_PAYMENT_METHOD_SponsoredProductsBillingErrorReason              SponsoredProductsBillingErrorReason = "EXPIRED_PAYMENT_METHOD"
	PAYMENT_PROFILE_NOT_FOUND_SponsoredProductsBillingErrorReason           SponsoredProductsBillingErrorReason = "PAYMENT_PROFILE_NOT_FOUND"
	VETTING_FAILURE_SponsoredProductsBillingErrorReason                     SponsoredProductsBillingErrorReason = "VETTING_FAILURE"
)
