/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type SptorBudgetRecommendationError struct {
	// The HTTP status code of the response.
	Code string `json:"code,omitempty"`
	// A human-readable description of the response.
	Details string `json:"details,omitempty"`
}
