/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// Represents the range of rule attribute value. NOT SUPPORTED right now
type OptimizationRulesApiSwaggerRangeTypeRuleCriteria struct {
	MaxValue float64 `json:"maxValue"`
	MinValue float64 `json:"minValue"`
}
