/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// A product target.
type SponsoredProductsProductTargetV2 struct {
	// The adGroupId of the destination manual-targeting adGroup where the target belongs.
	DestinationAdGroupId string `json:"destinationAdGroupId,omitempty"`
	// The the expression type (for PRODUCT). One of PRODUCT_EXACT, PRODUCT_SIMILAR
	ExpressionType string `json:"expressionType,omitempty"`
	// The product ASIN of the target.
	Target string `json:"target,omitempty"`
	// The id of the product target.
	TargetId string `json:"targetId,omitempty"`
	// The id of the target promotion group.
	TargetPromotionGroupId string `json:"targetPromotionGroupId,omitempty"`
}
