/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type SponsoredProductsThrottlingExceptionCode string

// List of SponsoredProductsThrottlingExceptionCode
const (
	THROTTLED_SponsoredProductsThrottlingExceptionCode SponsoredProductsThrottlingExceptionCode = "THROTTLED"
)
