/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type SponsoredProductsInternalServerExceptionCode string

// List of SponsoredProductsInternalServerExceptionCode
const (
	INTERNAL_SERVER_EXCEPTION_SponsoredProductsInternalServerExceptionCode SponsoredProductsInternalServerExceptionCode = "INTERNAL_SERVER_EXCEPTION"
)
