/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type SponsoredProductsInvalidInputErrorReason string

// List of SponsoredProductsInvalidInputErrorReason
const (
	INVALID_TOKEN_SponsoredProductsInvalidInputErrorReason SponsoredProductsInvalidInputErrorReason = "INVALID_TOKEN"
)
