/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type SponsoredProductsUpdateSponsoredProductsAdGroupsRequestContent struct {
	// An array of adGroups with updated values.
	AdGroups []SponsoredProductsUpdateAdGroup `json:"adGroups"`
}
