/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// Response object of failed target promotion group target.
type SponsoredProductsCreateTargetPromotionGroupTargetsFailureResponseItem struct {
	// Response object of failed target promotion group target.
	Errors []SponsoredProductsCreateTargetError `json:"errors,omitempty"`
	// The expression type of the target that was requested to be created.
	ExpressionType string `json:"expressionType,omitempty"`
	// The target that was requested to be created.
	Target string `json:"target,omitempty"`
}
