/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// Error that represents failure due to API caller exceeding allowed service limits.
type SponsoredProductsThrottledError struct {
	Cause *SponsoredProductsErrorCause `json:"cause,omitempty"`
	// Human readable error message
	Message string                                 `json:"message"`
	Reason  *SponsoredProductsThrottledErrorReason `json:"reason"`
}
