/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// This request type is used to retrieve recommended keyword targets for ASINs. Set the recommendationType to KEYWORDS_FOR_ASINS to use this request type.
type RankedKeywordTargetsForAsinsRequest struct {
	// A list of targets that need to be ranked
	Targets []Object `json:"targets,omitempty"`
	// An array list of Asins
	Asins []string `json:"asins"`
	// The bid recommendations returned will depend on the bidding strategy. <br> LEGACY_FOR_SALES - Dynamic Bids (Down only) <br> AUTO_FOR_SALES - Dynamic Bids (Up or down) <br> MANUAL - Fixed Bids
	BiddingStrategy string `json:"biddingStrategy,omitempty"`
	// Set this parameter to false if you do not want to retrieve bid suggestions for your keyword targets. Defaults to true.
	BidsEnabled        bool              `json:"bidsEnabled,omitempty"`
	ProductDetailsList *[]ProductDetails `json:"productDetailsList,omitempty"`
	// The recommendationType to retrieve recommended keyword targets for a list of ASINs.
	RecommendationType string `json:"recommendationType"`
}
