/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// Errors related to product identifiers
type SponsoredProductsProductIdentifierError struct {
	Cause       *SponsoredProductsErrorCause  `json:"cause,omitempty"`
	Marketplace *SponsoredProductsMarketplace `json:"marketplace,omitempty"`
	// Human readable error message
	Message string                                         `json:"message"`
	Reason  *SponsoredProductsProductIdentifierErrorReason `json:"reason"`
}
