/*
 * Sponsored Products
 *
 *  
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

// Exception resulting in mutating campaign management entities
type SponsoredProductsNegativeKeywordMutationExceptionResponseContent struct {
	Code *SponsoredProductsInvalidArgumentErrorCode `json:"code"`
	Errors []SponsoredProductsNegativeKeywordMutationError `json:"errors,omitempty"`
	// Human readable error message
	Message string `json:"message"`
}
