/*
 * Sponsored Products
 *
 *
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredproductsv3

type SponsoredProductsExistingAdGroup struct {
	// The id of the Ad Group.
	AdGroupId string `json:"adGroupId"`
}
