/*
 * Measurement
 *
 * Measurement management.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dspmeasurement
// AssetTypeV1M2 : The type of the Asset.
type AssetTypeV1M2 string

// List of AssetTypeV1M2
const (
	IMAGE_AssetTypeV1M2 AssetTypeV1M2 = "IMAGE"
	VIDEO_AssetTypeV1M2 AssetTypeV1M2 = "VIDEO"
)
