/*
 * Measurement
 *
 * Measurement management.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dspmeasurement

// The placeholder candidate in Survey question.
type SurveyQuestionPlaceholderCandidateV1 struct {
	// Whether custom value is allowed for the placeholder.
	AllowCustomValue bool `json:"allowCustomValue,omitempty"`
	// Allowed value ranges for placeholder. Only applicable if the valueType is INTEGER.
	AllowedValueRanges []SurveyQuestionPlaceholderAllowedRangeV1 `json:"allowedValueRanges,omitempty"`
	// Allowed values for placeholder. Will be empty if placeholder is free text field.
	AllowedValues []SurveyQuestionPlaceholderAllowedValueV1 `json:"allowedValues,omitempty"`
	// Default values that will be appended to the values list regardless.
	DefaultValues []string `json:"defaultValues,omitempty"`
	// The survey question placeholder field name.
	FieldName string `json:"fieldName,omitempty"`
	// Where the placeholder values will be inferred from.
	InferredFields []string `json:"inferredFields,omitempty"`
	// The maximum allowed character length for each individual placeholder value.
	MaximumValueLength int32 `json:"maximumValueLength,omitempty"`
	// The minimum allowed character length for each individual placeholder value.
	MinimumValueLength int32 `json:"minimumValueLength,omitempty"`
	ValueType *PlaceholderValueTypeV1 `json:"valueType,omitempty"`
}
