/*
 * Measurement
 *
 * Measurement management.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dspmeasurement

// The request object to fetch measurement vendor products.
type VendorProductRequestV1M1 struct {
	// AdType filters to be applied when fetching measurement vendor products. If not supplied we will include all available vendor products.
	AdTypeFilters []AdTypeV1 `json:"adTypeFilters,omitempty"`
	// FundingType filters to be applied when fetching measurement vendor products. If not supplied we will include all available vendor products.
	FundingTypeFilters []FundingTypeV1M1 `json:"fundingTypeFilters,omitempty"`
	// StudyObjective filters to be applied when fetching measurement vendor products. If not supplied we will include all available vendor products.
	ObjectiveTypeFilters []StudyObjectiveV1 `json:"objectiveTypeFilters,omitempty"`
	// StudyType filters to be applied when fetching measurement vendor products. If not supplied we will include all available vendor products.
	StudyTypeFilters []StudyTypeV1 `json:"studyTypeFilters,omitempty"`
	// VendorProduct identifier filters to be applied when fetching measurement vendor products. If not supplied we will include all available vendor products.
	VendorProductIdFilters []string `json:"vendorProductIdFilters,omitempty"`
	// VendorType filters to be applied when fetching measurement vendor products. If not supplied we will include all available vendor products.
	VendorTypeFilters []VendorTypeV1M1 `json:"vendorTypeFilters,omitempty"`
}
