/*
 * Measurement
 *
 * Measurement management.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dspmeasurement

// StudySubmissionTypeV1 : The submission type for the creation and updating of studies. Currently, this submission type is supported for brand lift studies only.  This is an optional parameter in each of the request objects and its default value is `SUBMISSION` if not provided. A value of `SUBMISSION` indicates that a study should be submitted for approval. A value of `DRAFT` indicates that a study should be saved but not submitted.
type StudySubmissionTypeV1 string

// List of StudySubmissionTypeV1
const (
	DRAFT_StudySubmissionTypeV1      StudySubmissionTypeV1 = "DRAFT"
	SUBMISSION_StudySubmissionTypeV1 StudySubmissionTypeV1 = "SUBMISSION"
)
