/*
 * Measurement
 *
 * Measurement management.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dspmeasurement

// FundingTypeV1M1 : The measurement funding type. For COMPLIMENTARY studies the cost will be covered by Amazon.
type FundingTypeV1M1 string

// List of FundingTypeV1M1
const (
	COMPLIMENTARY_FundingTypeV1M1       FundingTypeV1M1 = "COMPLIMENTARY"
	THIRD_PARTY_PAYMENT_FundingTypeV1M1 FundingTypeV1M1 = "THIRD_PARTY_PAYMENT"
)
