/*
 * Measurement
 *
 * Measurement management.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dspmeasurement

// The basic model for all DSP CREATIVE_TESTING objective studies.
type DspCreativeTestingMetadataV1M2 struct {
	// A list of assets to be used for the creative testing study as part of either the survey question or the response. In case of API responses, number of assets returned would be limited to 10 even if a creative testing study has more than 10 assets associated with it.
	Assets []AssetV1M2 `json:"assets,omitempty"`
	AudienceTargetingGroup *AudienceTargetingGroupV1M2 `json:"audienceTargetingGroup,omitempty"`
	// The study brand name.
	BrandName string `json:"brandName,omitempty"`
	// Optional study product category.
	ProductCategory string `json:"productCategory,omitempty"`
}
