/*
 * Measurement
 *
 * Measurement management.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dspmeasurement
// EligibilityIssueSeverityV1 : Supported values are WARNING, ERROR. ERROR severity issues need to be resolved while WARNING severity issues can be ignored.
type EligibilityIssueSeverityV1 string

// List of EligibilityIssueSeverityV1
const (
	ERROR__EligibilityIssueSeverityV1 EligibilityIssueSeverityV1 = "ERROR"
	WARNING_EligibilityIssueSeverityV1 EligibilityIssueSeverityV1 = "WARNING"
)
