/*
 * Measurement
 *
 * Measurement management.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dspmeasurement

// VendorTypeV1M2 : The measurement vendor type, each study type will have different supported vendors.
type VendorTypeV1M2 string

// List of VendorTypeV1M2
const (
	AMAZON_VendorTypeV1M2              VendorTypeV1M2 = "AMAZON"
	OMNICHANNEL_METRICS_VendorTypeV1M2 VendorTypeV1M2 = "OMNICHANNEL_METRICS"
)
