/*
 * Measurement
 *
 * Measurement management.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dspmeasurement

// StudyTypeV1M2 : The study type.
type StudyTypeV1M2 string

// List of StudyTypeV1M2
const (
	AUDIENCE_RESEARCH_StudyTypeV1M2   StudyTypeV1M2 = "AUDIENCE_RESEARCH"
	BRAND_LIFT_StudyTypeV1M2          StudyTypeV1M2 = "BRAND_LIFT"
	CREATIVE_TESTING_StudyTypeV1M2    StudyTypeV1M2 = "CREATIVE_TESTING"
	OMNICHANNEL_METRICS_StudyTypeV1M2 StudyTypeV1M2 = "OMNICHANNEL_METRICS"
)
