/*
 * Measurement
 *
 * Measurement management.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dspmeasurement

// A list of studies.
type PaginatedBaseStudiesV1M1 struct {
	Measurements []BaseStudyV1M1 `json:"measurements,omitempty"`
	NextToken string `json:"nextToken,omitempty"`
}
