/*
 * Measurement
 *
 * Measurement management.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dspmeasurement

// The grid question response object. Only applicable for SINGLE_SELECT_GRID type question.
type GridQuestionResponsesV1M1 struct {
	Columns []SurveyQuestionPlaceholderFieldValueV1 `json:"columns,omitempty"`
	Rows    []SurveyQuestionPlaceholderFieldValueV1 `json:"rows,omitempty"`
}
