/*
 * Measurement
 *
 * Measurement management.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dspmeasurement

// The requirement for specific survey question category.
type SurveyQuestionCategoryRequirementV1M1 struct {
	Category *SurveyQuestionCategoryV1M1 `json:"category,omitempty"`
	// The maximum number of questions required for the question category.
	MaximumQuestions int32 `json:"maximumQuestions,omitempty"`
	// The minimum number of questions required for the question category.
	MinimumQuestions int32 `json:"minimumQuestions,omitempty"`
}
