/*
 * Insights
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package insights

// Information about any audience included in the response.
type InsightsAudiencesOverlapAudienceMetadataV2 struct {
	AudienceForecast *InsightsAudiencesOverlapAudienceMetadataV2AudienceForecast `json:"audienceForecast,omitempty"`
	// The identifier of an audience.
	AudienceId string `json:"audienceId"`
	// The type of the overlapping audience.
	Category string `json:"category"`
	// Audience name
	Name string `json:"name"`
}
