/*
 * ADSP Audiences
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dspaudiences

// The success response object.
type DspAudienceSuccessItem struct {
	// The audience identifier.
	AudienceId string `json:"audienceId"`
	// The UUID provided in the request for creation of this audience.
	IdempotencyKey string `json:"idempotencyKey"`
	// The index of the DspAudienceCreateRequestItem from the request, e.g. 1st item in the batch request will correspond to index 0 in the response.
	Index int32 `json:"index"`
}
