/*
 * Ad Library API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package adlibrary
import (
	"time"
)

type ListAdsRequestContent struct {
	// This parameter will limit results to those matching the requested advertisement purpose. This includes the name of the product, service, or brand within the ad or affiliate marketing content.
	AdvertisementPurpose string `json:"advertisementPurpose,omitempty"`
	// The person or entity on whose behalf the ad or affiliate marketing content is presented. This parameter will limit results to advertisement summaries matching the requested advertiser name.
	AdvertiserName string `json:"advertiserName,omitempty"`
	// When specified, limits results to those with delivery date after the specified date string. The date string is specified in ISO format (YYYY-MM-DD) in UTC timezone. For example: 2020-12-16.
	DeliveryAfterDateUtc time.Time `json:"deliveryAfterDateUtc,omitempty"`
	// When specified, limits results to those with a delivery date prior to the specified date string. The date string is specified in ISO format (YYYY-MM-DD) in UTC timezone. For example: 2020-12-16.
	DeliveryBeforeDateUtc time.Time `json:"deliveryBeforeDateUtc,omitempty"`
	// Whether the advertisement was paused, removed or suppressed based on alleged illegality or incompatibility with terms and conditions. Limits results based on their restriction status.
	IsRestricted bool `json:"isRestricted,omitempty"`
	// Defaults to 10, with supported values between 1 and 1000.     If the size of the result set is larger than the limit, callers will retrieve additional results through pagination parameters.
	MaxResults float64 `json:"maxResults,omitempty"`
	NameMatchType *NameMatchType `json:"nameMatchType,omitempty"`
	// Pagination token to retrieve the next set of results.     Callers must make use of the token provided in a previous response to use this parameter.
	NextToken string `json:"nextToken,omitempty"`
	// When specified, limits results based on their delivery to a particular Amazon EU store (e.g., amazon.de, amazon.fr).
	SiteName string `json:"siteName,omitempty"`
}
