/*
 * Sponsored TV
 *
 * This API allows users to perform Sponsored TV operations.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredtv

type AdGroupServingStatus string

// List of AdGroupServingStatus
const (
	ACCOUNT_OUT_OF_BUDGET_AdGroupServingStatus AdGroupServingStatus = "ACCOUNT_OUT_OF_BUDGET"
	ADGROUP_POLICING_CREATIVE_REJECTED_AdGroupServingStatus AdGroupServingStatus = "ADGROUP_POLICING_CREATIVE_REJECTED"
	ADGROUP_POLICING_PENDING_REVIEW_AdGroupServingStatus AdGroupServingStatus = "ADGROUP_POLICING_PENDING_REVIEW"
	ADVERTISER_ARCHIVED_AdGroupServingStatus AdGroupServingStatus = "ADVERTISER_ARCHIVED"
	ADVERTISER_EXCEED_SPENDS_LIMIT_AdGroupServingStatus AdGroupServingStatus = "ADVERTISER_EXCEED_SPENDS_LIMIT"
	ADVERTISER_PAUSED_AdGroupServingStatus AdGroupServingStatus = "ADVERTISER_PAUSED"
	ADVERTISER_PAYMENT_FAILURE_AdGroupServingStatus AdGroupServingStatus = "ADVERTISER_PAYMENT_FAILURE"
	ADVERTISER_STATUS_ENABLED_AdGroupServingStatus AdGroupServingStatus = "ADVERTISER_STATUS_ENABLED"
	AD_GROUP_ARCHIVED_AdGroupServingStatus AdGroupServingStatus = "AD_GROUP_ARCHIVED"
	AD_GROUP_INCOMPLETE_AdGroupServingStatus AdGroupServingStatus = "AD_GROUP_INCOMPLETE"
	AD_GROUP_LOW_BID_AdGroupServingStatus AdGroupServingStatus = "AD_GROUP_LOW_BID"
	AD_GROUP_PAUSED_AdGroupServingStatus AdGroupServingStatus = "AD_GROUP_PAUSED"
	AD_GROUP_POLICING_CREATIVE_REJECTED_AdGroupServingStatus AdGroupServingStatus = "AD_GROUP_POLICING_CREATIVE_REJECTED"
	AD_GROUP_POLICING_PENDING_REVIEW_AdGroupServingStatus AdGroupServingStatus = "AD_GROUP_POLICING_PENDING_REVIEW"
	AD_GROUP_STATUS_ENABLED_AdGroupServingStatus AdGroupServingStatus = "AD_GROUP_STATUS_ENABLED"
	AD_POLICING_PENDING_REVIEW_AdGroupServingStatus AdGroupServingStatus = "AD_POLICING_PENDING_REVIEW"
	CAMPAIGN_ARCHIVED_AdGroupServingStatus AdGroupServingStatus = "CAMPAIGN_ARCHIVED"
	CAMPAIGN_INCOMPLETE_AdGroupServingStatus AdGroupServingStatus = "CAMPAIGN_INCOMPLETE"
	CAMPAIGN_OUT_OF_BUDGET_AdGroupServingStatus AdGroupServingStatus = "CAMPAIGN_OUT_OF_BUDGET"
	CAMPAIGN_PAUSED_AdGroupServingStatus AdGroupServingStatus = "CAMPAIGN_PAUSED"
	ENDED_AdGroupServingStatus AdGroupServingStatus = "ENDED"
	INELIGIBLE_AdGroupServingStatus AdGroupServingStatus = "INELIGIBLE"
	OTHER_AdGroupServingStatus AdGroupServingStatus = "OTHER"
	PENDING_START_DATE_AdGroupServingStatus AdGroupServingStatus = "PENDING_START_DATE"
	STATUS_UNAVAILABLE_AdGroupServingStatus AdGroupServingStatus = "STATUS_UNAVAILABLE"
)
