/*
 * Sponsored TV
 *
 * This API allows users to perform Sponsored TV operations.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredtv

type DefaultBid struct {
	// The amount of the default bid associated with the ad group. Used if no bid is specified.
	Bid float64 `json:"bid,omitempty"`
}
