/*
 * Sponsored TV
 *
 * This API allows users to perform Sponsored TV operations.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredtv

// Simplified Location Targeting Clause for Forecast
type ForecastLocationTargetingClause struct {
	// The category of the location, including DMA, CITY, POSTAL_CODE and so on.
	Category string `json:"category,omitempty"`
	// The Location Geo ACI (Amazon Common Identifier).
	LocationId string `json:"locationId"`
	// The human readable location information.
	LocationIdResolved string `json:"locationIdResolved,omitempty"`
}
