/*
 * Sponsored TV
 *
 * This API allows users to perform Sponsored TV operations.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredtv

type Forecast struct {
	Metric *ForecastMetricType `json:"metric,omitempty"`
	Value  *ForecastValue      `json:"value,omitempty"`
}
