/*
 * Sponsored TV
 *
 * This API allows users to perform Sponsored TV operations.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredtv

type ListSponsoredTvCampaignsRequestContent struct {
	CampaignIdFilter           *ObjectIdFilter `json:"campaignIdFilter,omitempty"`
	FullFunnelCampaignIdFilter *ObjectIdFilter `json:"fullFunnelCampaignIdFilter,omitempty"`
	// Number of records to include in the paginated response. Defaults to max page size for given API.
	MaxResults int32       `json:"maxResults,omitempty"`
	NameFilter *NameFilter `json:"nameFilter,omitempty"`
	// Token value allowing to navigate to the next response page.
	NextToken   string             `json:"nextToken,omitempty"`
	StateFilter *EntityStateFilter `json:"stateFilter,omitempty"`
}
