/*
 * Sponsored TV
 *
 * This API allows users to perform Sponsored TV operations.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredtv

type CreateSponsoredTvAdsRequestContent struct {
	// An array of Sponsored TV ads.
	Ads []CreateAd `json:"ads"`
}
