/*
 * Sponsored TV
 *
 * This API allows users to perform Sponsored TV operations.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredtv

// Forecast Errors just targeting on the general forecast error type
type ForecastOtherError struct {
	Cause *ErrorCause `json:"cause"`
	// Human readable error message.
	Message string `json:"message"`
	// Reason for forecast other error
	Reason string `json:"reason"`
}
