/*
 * Sponsored TV
 *
 * This API allows users to perform Sponsored TV operations.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredtv

// Structure describing error cause - location in the payload and data causing error.
type ErrorCause struct {
	// Error location, JSON Path expression specifying element of API payload causing error.
	Location string `json:"location"`
	// Optional value causing error.
	Trigger string `json:"trigger,omitempty"`
}
