/*
 * Sponsored TV
 *
 * This API allows users to perform Sponsored TV operations.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredtv

type CreateSponsoredTvCampaignsRequestContent struct {
	Campaigns []CreateCampaign `json:"campaigns"`
}
