/*
 * Sponsored TV
 *
 * This API allows users to perform Sponsored TV operations.
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sponsoredtv

type AdFailureResponseItem struct {
	// A list of validation errors.
	Errors []AdMutationError `json:"errors,omitempty"`
	// The index of the ad in the array from the request body.
	Index int32 `json:"index"`
}
